apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-amqp-rabbit
  namespace: vdi
data:
  MINIO_NOTIFY_AMQP_ENABLE_RABBIT: "on"
  MINIO_NOTIFY_AMQP_URL_RABBIT: amqp://${GLOBAL_RABBIT_USERNAME:?}:${GLOBAL_RABBIT_PASSWORD:?}@${GLOBAL_RABBIT_HOST:?}:${GLOBAL_RABBIT_PORT:-5672}
  MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT: ${GLOBAL_RABBIT_VDI_EXCHANGE_NAME:?}
  MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT: ${GLOBAL_RABBIT_VDI_EXCHANGE_TYPE:-direct}
  MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT: ${GLOBAL_RABBIT_VDI_ROUTING_KEY:?}
  MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT: 2
  MINIO_NOTIFY_AMQP_DURABLE_RABBIT: "on"
