#%RAML 1.0 Library

uses:
  common: ../../../../common.raml

types:
  ShareOfferEntry:
    displayName: Share Offer Details
    additionalProperties: false
    properties:
      datasetId: common.VdiId
      owner: common.DatasetOwner
      shareStatus: ShareOfferStatus
      datasetType: common.DatasetTypeOutput
      projectIds:
        type: common.ProjectId[]
        minItems: 1
        uniqueItems: true

  ShareOfferStatus:
    displayName: Share Offer Status
    type: string
    enum:
    - open
    - accepted
    - rejected
