#%RAML 1.0 Overlay
extends: api.raml

# Non-deprecated endpoints up here to preserve ordering in rendered HTML.

/datasets: {}
/datasets/{vdi-id}: {}
/datasets/{vdi-id}/files: {}
/datasets/{vdi-id}/shares/{recipient-user-id}: {}
/datasets/community: {}
/users: {}
/plugins: {}
/admin: {}
/api: {}
/health: {}
/metrics: {}


# Deprecated endpoints

/vdi-datasets:
  displayName: "/vdi-datasets"
  get:
    description: Deprecated alias of [/datasets](#resources:/datasets:get)
  post:
    description: Deprecated alias of [/datasets](#resources:/datasets:post)

/vdi-datasets/community:
  displayName: /vdi-datasets/community
  get:
    description: Deprecated alias of [/datasets/community](#resources:/datasets/community:get)

/vdi-datasets/{vdi-id}:
  displayName: "/vdi-datasets/{vdi-id}"
  get:
    description: Deprecated alias of [/datasets/{vdi-id}](#resources:/datasets/{vd-id}:get)
  patch:
    description: Deprecated alias of [/datasets/{vdi-id}](#resources:/datasets/{vd-id}:patch)
  delete:
    description: Deprecated alias of [/datasets/{vdi-id}](#resources:/datasets/{vd-id}:delete)

/vdi-datasets/{vdi-id}/files:
  displayName: "/vdi-datasets/{vdi-id}/files"
  get:
    description: Deprecated alias of [/datasets/{vdi-id}/files](#resources:/datasets/{vdi-id}/files:get)
  /upload:
    get:
      description: Deprecated alias of [/datasets/{vdi-id}/files](#resources:/datasets/{vdi-id}/files/upload:get)
  /data:
    get:
      description: Deprecated alias of [/datasets/{vdi-id}/files](#resources:/datasets/{vdi-id}/files/data:get)

/vdi-datasets/{vdi-id}/shares/{recipient-user-id}:
  displayName: /vdi-datasets/{vdi-id}/shares/{recipient-user-id}
  /offer:
    displayName: /offer
    put:
      description: Deprecated alias of [/datasets/{vdi-id}/shares/{recipient-user-id}/offer](#resources:/datasets/{vdi-id}/shares/{recipient-user-id}/offer:put)
  /receipt:
    displayName: /receipt
    put:
      description: Deprecated alias of [/datasets/{vdi-id}/shares/{recipient-user-id}/receipt](#resources:/datasets/{vdi-id}/shares/{recipient-user-id}/receipt:put)

/vdi-datasets/share-offers:
  displayName: /vdi-datasets/share-offers
  get:
    description: Deprecated alias of [/users/self/share-offers](#resources:/users/self/share-offers:get)

/vdi-users:
  displayName: /vdi-users
  /self:
    /meta:
      get:
        description: Deprecated alias of [/users/self/meta](#resources:/users/self/meta:get)

/vdi-plugins:
  displayName: /vdi-plugins
  get:
    description: Deprecated alias of [/plugins](#resources:/plugins:get)
