#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.2.0/libraries/base-service.raml

title: VEuPathDB Dataset Installer
version: 1.7.0
mediaType: application/json

uses:
  lib: schema/types/library.raml


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃  ENDPOINT PATHS                                                          ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #

/datasets: !include schema/resources/dataset-list/resource.raml
/datasets/community: !include schema/resources/community-datasets/resource.raml
/datasets/{vdi-id}: !include schema/resources/dataset/resource.raml
/datasets/{vdi-id}/files: !include schema/resources/dataset-files/resource.raml
/datasets/{vdi-id}/shares/{recipient-user-id}: !include schema/resources/dataset-shares/resource.raml

/users: !include schema/resources/users/resource.raml
/plugins: !include schema/resources/plugins/resource.raml

/admin: !include schema/resources/admin/resource.raml


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃  DEPRECATED ENDPOINT PATHS                                               ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #

/vdi-datasets: !include schema/resources/dataset-list/resource.raml
/vdi-datasets/community: !include schema/resources/community-datasets/resource.raml
/vdi-datasets/{vdi-id}: !include schema/resources/dataset/resource.raml
/vdi-datasets/{vdi-id}/files: !include schema/resources/dataset-files/resource.raml
/vdi-datasets/{vdi-id}/shares/{recipient-user-id}: !include schema/resources/dataset-shares/resource.raml
/vdi-datasets/share-offers: !include schema/resources/users/self/share-offers/resource.raml
/vdi-plugins: !include schema/resources/plugins/resource.raml
/vdi-users: !include schema/resources/users/resource.raml
