#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.2.0/libraries/base-service.raml

title: VEuPathDB Dataset Installer
version: 1.7.0
mediaType: application/json
baseUri: https://veupathdb.org/vdi

uses:
  lib: api-schema/types/library.raml

securitySchemes:
  AdminToken:
    type: x-header-token
    displayName: Admin Token
    description: Per-service admin token header.
    describedBy:
      responses:
        401:
          body: lib.UnauthorizedError
  WdkAuth:
    type: x-vpdb-oath
    displayName: VEuPathDB OAuth 2.0
    describedBy:
      responses:
        401:
          body: lib.UnauthorizedError

traits:
  PaginatedList:
    queryParameters:
      limit?:
        description: Result count limit.  If set to `-1`, no limit is applied.
        type: integer
        default: 100
      offset?:
        description: Pagination offset.  Ignored if `limit < 0`.
        type: integer
        minimum: 0
        default: 0

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃  ENDPOINT PATHS                                                          ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #

/datasets: !include api-schema/resources/dataset-list/resource.raml
/datasets/{vdi-id}: !include api-schema/resources/dataset/resource.raml
/datasets/{vdi-id}/files: !include api-schema/resources/dataset-files/resource.raml
/datasets/{vdi-id}/shares/{recipient-user-id}: !include api-schema/resources/dataset-shares/resource.raml
/datasets/community: !include api-schema/resources/community-datasets/resource.raml

/users: !include api-schema/resources/users/resource.raml
/plugins: !include api-schema/resources/plugins/resource.raml

/admin/reports: !include api-schema/resources/admin/reports/resource.raml
/admin/rpc: !include api-schema/resources/admin/rpc/resource.raml

/meta-info: !include api-schema/resources/meta/resource.raml
