version: 2

updates:
- package-ecosystem: gradle
  registries:
  - github-packages
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.gusdb:fgputil*
  directory: "/"
  groups:
    test-dependencies:
      patterns:
      - org.junit.*
      - org.mockito.*
    log4j:
      patterns:
      - org.apache.logging.*

- package-ecosystem: docker
  directory: "/project/core"
  schedule:
    interval: monthly

registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/veupathdb/maven-packages
    username: ${{ secrets.PACKAGES_USER }}
    password: ${{ secrets.PACKAGES_KEY }}
