services:

  forward-ldap-1:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_LDAP_1}:389:${FORWARD_LDAP_1}:389",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_LDAP_1?:}

  forward-ldap-2:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_LDAP_2}:389:${FORWARD_LDAP_2}:389",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_LDAP_2?:}

  forward-s3:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_S3}:9000:${FORWARD_S3}:9000",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_S3?:}

  forward-db-1:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_1}:1521:${FORWARD_DB_1}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_1?:}

  forward-db-2:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_2}:1521:${FORWARD_DB_2}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_2?:}

  forward-db-3:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_3}:1521:${FORWARD_DB_3}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_3?:}

  forward-db-4:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_4}:1521:${FORWARD_DB_4}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_4?:}

  forward-db-5:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_5}:1521:${FORWARD_DB_5}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_5?:}

  forward-db-6:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_6}:1521:${FORWARD_DB_6}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_6?:}

  forward-db-7:
    image: kroniak/ssh-client:3.19
    volumes:
    - type: bind
      source: ${SSH_AUTH_SOCKET_SOURCE:-$SSH_AUTH_SOCK}
      target: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    - type: bind
      source: $HOME/.ssh/known_hosts
      target: /root/.ssh/known_hosts
      read_only: true
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCKET_TARGET:-$SSH_AUTH_SOCK}
    entrypoint: [
      "ssh", "-tNn", "-p", "${TUNNEL_PORT:?}", "-o", "ServerAliveInterval=60",
      "-L", "${FORWARD_DB_7}:1521:${FORWARD_DB_7}:1521",
      "${TUNNEL_USER:?}@${TUNNEL_HOST:?}"
    ]
    networks:
      internal:
        aliases:
        - ${FORWARD_DB_7?:}

  #
  # Links for actual stack containers
  #

  service:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7

  plugin-bigwig:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7

  plugin-biom:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7

  plugin-example:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7

  plugin-genelist:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7

  plugin-isasimple:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7

  plugin-rnaseq:
    depends_on:
    - forward-ldap-1
    - forward-ldap-2
    - forward-s3
    - forward-db-1
    - forward-db-2
    - forward-db-3
    - forward-db-4
    - forward-db-5
    - forward-db-6
    - forward-db-7
