version: "3.5"

networks:
  internal:
  traefik:
    external: true
  monitoring-ext:
    external: true
  rabbitmq:
    # Rabbit is local then the network is defined externally (set this to true)
    #
    # If rabbit is not local then the network is not defined externally and we
    # need to define it ourselves (set this to false)
    external: ${RABBITMQ_IS_LOCAL:-false}

volumes:
  cache-db-data:

services:
  cache-db:
    image: veupathdb/vdi-internal-db:${VDI_CACHE_DB_TAG:-latest}
    environment:
      POSTGRES_USER: ${CACHE_DB_USERNAME:?}
      POSTGRES_PASSWORD: ${CACHE_DB_PASSWORD:?}
      POSTGRES_DB: ${CACHE_DB_NAME:?}
    healthcheck:
      test: "pg_isready -U ${CACHE_DB_USERNAME:?} -d ${CACHE_DB_NAME:?}"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - internal
    volumes:
    - cache-db-data:/var/lib/postgresql/data
    labels:
    - "com.centurylinklabs.watchtower.enable=${VDI_POSTGRES_WATCHTOWER:-false}"

  kafka:
    image: veupathdb/apache-kafka:${VDI_KAFKA_TAG:-latest}
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://kafka:9092}
    networks:
    - internal

  service:
    image: veupathdb/vdi-service:${VDI_SERVICE_TAG:-latest}
    depends_on:
    - cache-db
    - kafka
    links:
    - cache-db
    - kafka
    - plugin-bigwig
    - plugin-biom
    - plugin-example
    - plugin-genelist
    - plugin-isasimple
    - plugin-rnaseq
    - plugin-wrangler
    networks:
    - internal
    - traefik
    - monitoring-ext
    - rabbitmq

    stop_grace_period: 1m
    environment:
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN:?}

      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}

      CACHE_DB_USERNAME: ${CACHE_DB_USERNAME:?}
      CACHE_DB_PASSWORD: ${CACHE_DB_PASSWORD:?}

      GLOBAL_RABBIT_HOST: ${GLOBAL_RABBIT_HOST:?}
      GLOBAL_RABBIT_USERNAME: ${GLOBAL_RABBIT_USERNAME:?}
      GLOBAL_RABBIT_PASSWORD: ${GLOBAL_RABBIT_PASSWORD:?}

      S3_HOST: ${S3_HOST:?}
      S3_ACCESS_TOKEN: ${S3_ACCESS_TOKEN:?}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?}

      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}

    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${VDI_SERVICE_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.loadbalancer.server.port=${VDI_SERVICE_HTTP_PORT:-80}"
    - "traefik.http.routers.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.rule=Host(`${TRAEFIK_VDI_HOST:-vdi-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.tls=${USE_TRAEFIK_SSL:-true}"
    - "traefik.http.routers.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

  plugin-genelist:
    image: veupathdb/vdi-plugin-genelist:${VDI_PLUGIN_GENELIST_TAG:-latest}
    networks:
      internal:
        aliases:
        - genelist
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_GENELIST_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}

  plugin-isasimple:
    image: veupathdb/vdi-plugin-isasimple:${VDI_PLUGIN_ISASIMPLE_TAG:-latest}
    networks:
      internal:
        aliases:
        - isasimple
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_ISASIMPLE_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}

  plugin-bigwig:
    image: veupathdb/vdi-plugin-bigwig:${VDI_PLUGIN_BIGWIG_TAG:-latest}
    networks:
      internal:
        aliases:
        - bigwig
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_BIGWIG_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}

  plugin-biom:
    image: veupathdb/vdi-plugin-biom:${VDI_PLUGIN_BIOM_TAG:-latest}
    networks:
      internal:
        aliases:
        - biom
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_BIOM_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}

  plugin-rnaseq:
    image: veupathdb/vdi-plugin-rnaseq:${VDI_PLUGIN_RNASEQ_TAG:-latest}
    networks:
      internal:
        aliases:
        - rnaseq
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_RNASEQ_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}

  plugin-wrangler:
    image: veupathdb/vdi-plugin-wrangler:${VDI_PLUGIN_WRANGLER_TAG:-latest}
    networks:
      internal:
        aliases:
        - wrangler
      monitoring-ext: { }
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_WRANGLER_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}

      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}

      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}

      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}

      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}

      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}

      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}

      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}

      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}

      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}

      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}

      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}

      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}

      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}

      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}

      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}
