version: "3.5"

services:
  vdi-cache-db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ${QUEUE_DB_USERNAME:?}
      POSTGRES_PASSWORD: ${QUEUE_DB_PASSWORD:?}
    healthcheck:
      test: "pg_isready -U ${QUEUE_DB_USERNAME:?}"
      interval: 30s
      timeout: 10s
      retries: 5

  vdi-kafka:
    image: foxcapades/apache-kafka:3.4.0
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  vdi-service:
    image: veupathdb/vdi-service:${VDI_SERVICE_TAG:-latest}
    depends_on:
    - vdi-cache-db
    - vdi-kafka
    links:
    - vdi-cache-db
    - vdi-kafka
    environment:
      SERVER_PORT: ${VDI_SERVICE_HTTP_PORT:-80}

      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY:?}

      LDAP_SERVER: ${LDAP_SERVER:?}

      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}

      # Connection details for the global RabbitMQ instance.
      GLOBAL_RABBIT_USERNAME: ${GLOBAL_RABBIT_USERNAME:?}
      GLOBAL_RABBIT_PASSWORD: ${GLOBAL_RABBIT_PASSWORD:?}
      GLOBAL_RABBIT_HOST: ${GLOBAL_RABBIT_HOST:?}
      GLOBAL_RABBIT_PORT: ${GLOBAL_RABBIT_PORT:?}

      # Connection details for the stack-internal Kafka instance.
      KAFKA_HOST: ${KAFKA_HOST:-vdi-kafka}
      KAFKA_PORT: ${KAFKA_PORT:-9092}
      KAFKA_TOPIC_BUCKET_NOTIFICATIONS: ${KAFKA_TOPIC_BUCKET_NOTIFICATIONS:-bucket-notifications}
      KAFKA_TOPIC_IMPORT_TRIGGERS: ${KAFKA_TOPIC_IMPORT_TRIGGERS:-import-triggers}
      KAFKA_TOPIC_IMPORT_RESULTS: ${KAFKA_TOPIC_IMPORT_RESULTS:-import-results}
      KAFKA_TOPIC_INSTALL_TRIGGERS: ${KAFKA_TOPIC_INSTALL_TRIGGERS:-install-triggers}
      KAFKA_TOPIC_INSTALL_RESULTS: ${KAFKA_TOPIC_INSTALL_RESULTS:-install-results}
      KAFKA_TOPIC_UPDATE_META_TRIGGERS: ${KAFKA_TOPIC_UPDATE_META_TRIGGERS:-update-meta-triggers}
      KAFKA_TOPIC_UPDATE_META_RESULTS: ${KAFKA_TOPIC_UPDATE_META_RESULTS:-update-meta-results}
      KAFKA_TOPIC_DELETE_TRIGGERS: ${KAFKA_TOPIC_DELETE_TRIGGERS:-delete-triggers}
      KAFKA_TOPIC_DELETE_RESULTS: ${KAFKA_TOPIC_DELETE_RESULTS:-delete-results}
      KAFKA_TOPIC_SHARE_TRIGGERS: ${KAFKA_TOPIC_SHARE_TRIGGERS:-share-triggers}
      KAFKA_TOPIC_SHARE_RESULTS: ${KAFKA_TOPIC_SHARE_RESULTS:-share-results}

      # Connection details for the global S3 instance.
      S3_HOST: ${S3_HOST:?}
      S3_PORT: ${S3_PORT:-9000}
      S3_USE_HTTPS: ${S3_USE_HTTPS:-false}
      S3_ACCESS_TOKEN: ${S3_ACCESS_TOKEN:?}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?}
      S3_BUCKET_NAME: ${S3_BUCKET:?}

      # Connection details for the stack-internal Postgres instance.
      QUEUE_DB_USERNAME: ${QUEUE_DB_USERNAME:?}
      QUEUE_DB_PASSWORD: ${QUEUE_DB_PASSWORD:?}
      QUEUE_DB_HOST: ${QUEUE_DB_HOST:?}
      QUEUE_DB_PORT: ${QUEUE_DB_PORT:?}
      QUEUE_DB_NAME: ${QUEUE_DB_NAME:?}
      QUEUE_DB_POOL_SIZE: ${QUEUE_DB_POOL_SIZE:-5}

      # Account DB connection details
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME:?}
      ACCT_DB_USER: ${ACCT_DB_USERNAME:?}
      ACCT_DB_PASS: ${ACCT_DB_PASSWORD:?}
      ACCT_DB_POOL_SIZE: ${ACCT_DB_POOL_SIZE:-5}

      # Wildcard Environment Variables
      DB_CONNECTION_NAME_AMOEBA: ${DB_CONNECTION_NAME_AMOEBA:?}
      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA:?}
      DB_CONNECTION_USER_AMOEBA: ${DB_CONNECTION_USER_AMOEBA:?}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}
      DB_CONNECTION_POOL_SIZE_AMOEBA: ${DB_CONNECTION_POOL_SIZE_AMOEBA:-5}

      DB_CONNECTION_NAME_CRYPTO: ${DB_CONNECTION_NAME_CRYPTO:?}
      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO:?}
      DB_CONNECTION_USER_CRYPTO: ${DB_CONNECTION_USER_CRYPTO:?}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}
      DB_CONNECTION_POOL_SIZE_CRYPTO: ${DB_CONNECTION_POOL_SIZE_CRYPTO:-5}

      DB_CONNECTION_NAME_FUNGI: ${DB_CONNECTION_NAME_FUNGI:?}
      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI:?}
      DB_CONNECTION_USER_FUNGI: ${DB_CONNECTION_USER_FUNGI:?}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}
      DB_CONNECTION_POOL_SIZE_FUNGI: ${DB_CONNECTION_POOL_SIZE_FUNGI:-5}

      DB_CONNECTION_NAME_GIARDIA: ${DB_CONNECTION_NAME_GIARDIA:?}
      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA:?}
      DB_CONNECTION_USER_GIARDIA: ${DB_CONNECTION_USER_GIARDIA:?}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}
      DB_CONNECTION_POOL_SIZE_GIARDIA: ${DB_CONNECTION_POOL_SIZE_GIARDIA:-5}

      DB_CONNECTION_NAME_HOST: ${DB_CONNECTION_NAME_HOST:?}
      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST:?}
      DB_CONNECTION_USER_HOST: ${DB_CONNECTION_USER_HOST:?}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}
      DB_CONNECTION_POOL_SIZE_HOST: ${DB_CONNECTION_POOL_SIZE_HOST:-5}

      DB_CONNECTION_NAME_MICROSPORIDIA: ${DB_CONNECTION_NAME_MICROSPORIDIA:?}
      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA:?}
      DB_CONNECTION_USER_MICROSPORIDIA: ${DB_CONNECTION_USER_MICROSPORIDIA:?}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}
      DB_CONNECTION_POOL_SIZE_MICROSPORIDIA: ${DB_CONNECTION_POOL_SIZE_MICROSPORIDIA:-5}

      DB_CONNECTION_NAME_PIROPLASMA: ${DB_CONNECTION_NAME_PIROPLASMA:?}
      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA:?}
      DB_CONNECTION_USER_PIROPLASMA: ${DB_CONNECTION_USER_PIROPLASMA:?}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}
      DB_CONNECTION_POOL_SIZE_PIROPLASMA: ${DB_CONNECTION_POOL_SIZE_PIROPLASMA:-5}

      DB_CONNECTION_NAME_PLASMO: ${DB_CONNECTION_NAME_PLASMO:?}
      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO:?}
      DB_CONNECTION_USER_PLASMO: ${DB_CONNECTION_USER_PLASMO:?}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}
      DB_CONNECTION_POOL_SIZE_PLASMO: ${DB_CONNECTION_POOL_SIZE_PLASMO:-5}

      DB_CONNECTION_NAME_TOXO: ${DB_CONNECTION_NAME_TOXO:?}
      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO:?}
      DB_CONNECTION_USER_TOXO: ${DB_CONNECTION_USER_TOXO:?}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}
      DB_CONNECTION_POOL_SIZE_TOXO: ${DB_CONNECTION_POOL_SIZE_TOXO:-5}

      DB_CONNECTION_NAME_TRICH: ${DB_CONNECTION_NAME_TRICH:?}
      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH:?}
      DB_CONNECTION_USER_TRICH: ${DB_CONNECTION_USER_TRICH:?}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}
      DB_CONNECTION_POOL_SIZE_TRICH: ${DB_CONNECTION_POOL_SIZE_TRICH:-5}

      DB_CONNECTION_NAME_TRITRYP: ${DB_CONNECTION_NAME_TRITRYP:?}
      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP:?}
      DB_CONNECTION_USER_TRITRYP: ${DB_CONNECTION_USER_TRITRYP:?}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}
      DB_CONNECTION_POOL_SIZE_TRITRYP: ${DB_CONNECTION_POOL_SIZE_TRITRYP:-5}

      DB_CONNECTION_NAME_VECTOR: ${DB_CONNECTION_NAME_VECTOR:?}
      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR:?}
      DB_CONNECTION_USER_VECTOR: ${DB_CONNECTION_USER_VECTOR:?}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}
      DB_CONNECTION_POOL_SIZE_VECTOR: ${DB_CONNECTION_POOL_SIZE_VECTOR:-5}

      DB_CONNECTION_NAME_ORTHO: ${DB_CONNECTION_NAME_ORTHO:?}
      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO:?}
      DB_CONNECTION_USER_ORTHO: ${DB_CONNECTION_USER_ORTHO:?}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}
      DB_CONNECTION_POOL_SIZE_ORTHO: ${DB_CONNECTION_POOL_SIZE_ORTHO:-5}

      DB_CONNECTION_NAME_CLINEPI: ${DB_CONNECTION_NAME_CLINEPI:?}
      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI:?}
      DB_CONNECTION_USER_CLINEPI: ${DB_CONNECTION_USER_CLINEPI:?}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}
      DB_CONNECTION_POOL_SIZE_CLINEPI: ${DB_CONNECTION_POOL_SIZE_CLINEPI:-5}

      DB_CONNECTION_NAME_MICROBIOME: ${DB_CONNECTION_NAME_MICROBIOME:?}
      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME:?}
      DB_CONNECTION_USER_MICROBIOME: ${DB_CONNECTION_USER_MICROBIOME:?}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}
      DB_CONNECTION_POOL_SIZE_MICROBIOME: ${DB_CONNECTION_POOL_SIZE_MICROBIOME:-5}
