version: "3.5"

networks:
  monitoring-ext:
    external: false
  rabbitmq:
    external: false

services:
  minio-external:
    image: veupathdb/minio
    depends_on:
    - rabbit-external
    links:
    - rabbit-external
    ports:
    - "9000:9000"
    - "9001:9001"
    networks:
    - internal
    - rabbitmq
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_TOKEN:?}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:?}

      MINIO_NOTIFY_AMQP_ENABLE_RABBIT: "on"
      MINIO_NOTIFY_AMQP_URL_RABBIT: amqp://${GLOBAL_RABBIT_USERNAME:?}:${GLOBAL_RABBIT_PASSWORD:?}@${GLOBAL_RABBIT_HOST:?}:${GLOBAL_RABBIT_PORT:-5672}
      MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT: ${GLOBAL_RABBIT_VDI_EXCHANGE_NAME:?}
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT: ${GLOBAL_RABBIT_VDI_EXCHANGE_TYPE:-direct}
      MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT: ${GLOBAL_RABBIT_VDI_ROUTING_KEY:?}
      MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT: 2
      MINIO_NOTIFY_AMQP_DURABLE_RABBIT: "on"

    entrypoint: >
      /bin/sh -c "
      while ! nc -zv ${GLOBAL_RABBIT_HOST:?} ${GLOBAL_RABBIT_PORT:-5672}; do sleep 3; done;
      minio server --console-address ':9001' /data;
      "

  minio-create-buckets:
    image: veupathdb/minio-mc
    depends_on:
    - minio-external
    - rabbit-external
    networks:
    - internal
    entrypoint: >
      /bin/sh -c "
      while ! nc -zv minio-external 9000; do sleep 3; done;
      mc alias set minioc http://minio-external:9000 ${S3_ACCESS_TOKEN:?} ${S3_SECRET_KEY:?};
      mc mb minioc/${S3_BUCKET_NAME:?};
      mc policy set public minioc/${S3_BUCKET_NAME:?};
      mc event add minioc/${S3_BUCKET_NAME:?} arn:minio:sqs::RABBIT:amqp --event put,delete;
      exit 0;
      "

  rabbit-external:
    image: rabbitmq:3.11.13-management-alpine
    ports:
    - "5672:5672"
    - "9002:15672"
    networks:
    - rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${GLOBAL_RABBIT_USERNAME:?}
      RABBITMQ_DEFAULT_PASS: ${GLOBAL_RABBIT_PASSWORD:?}
    healthcheck:
      test: [ CMD, curl, -f, http://localhost:15672 ]
      interval: 30s
      timeout: 10s
      retries: 5

  cache-db:
    ports:
    - "5432:5432"

  kafka:
    ports:
    - "9092:9092"

  service:
    build:
      context: .
    depends_on:
    - cache-db
    - kafka
    - rabbit-external
    - minio-external
    - minio-create-buckets
    links:
    - rabbit-external
    - minio-external
    networks:
    - rabbitmq
    ports:
    - "8080:${VDI_SERVICE_HTTP_PORT:-80}"
