version: "3.5"

networks:
  monitoring-ext:
    external: false
  rabbitmq:
    external: false
  traefik:
    external: false

name: "vdi"

services:
  minio-external:
    image: veupathdb/minio
    depends_on:
    - rabbit-external
    links:
    - rabbit-external
    ports:
    - "9000:9000"
    - "9001:9001"
    networks:
    - internal
    - rabbitmq
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_TOKEN:?}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:?}

      MINIO_NOTIFY_AMQP_ENABLE_RABBIT: "on"
      MINIO_NOTIFY_AMQP_URL_RABBIT: amqp://${GLOBAL_RABBIT_USERNAME:?}:${GLOBAL_RABBIT_PASSWORD:?}@${GLOBAL_RABBIT_HOST:?}:${GLOBAL_RABBIT_PORT:-5672}
      MINIO_NOTIFY_AMQP_EXCHANGE_RABBIT: ${GLOBAL_RABBIT_VDI_EXCHANGE_NAME:?}
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_RABBIT: ${GLOBAL_RABBIT_VDI_EXCHANGE_TYPE:-direct}
      MINIO_NOTIFY_AMQP_ROUTING_KEY_RABBIT: ${GLOBAL_RABBIT_VDI_ROUTING_KEY:?}
      MINIO_NOTIFY_AMQP_DELIVERY_MODE_RABBIT: 2
      MINIO_NOTIFY_AMQP_DURABLE_RABBIT: "on"

    entrypoint: >
      /bin/sh -c "
      while ! nc -zv ${GLOBAL_RABBIT_HOST:?} ${GLOBAL_RABBIT_PORT:-5672}; do sleep 3; done;
      minio server --console-address ':9001' /data;
      "

  minio-create-buckets:
    image: veupathdb/minio-mc
    depends_on:
    - minio-external
    - rabbit-external
    networks:
    - internal
    entrypoint: >
      /bin/sh -c "
      while ! nc -zv minio-external 9000; do sleep 3; done;
      mc alias set minioc http://minio-external:9000 ${S3_ACCESS_TOKEN:?} ${S3_SECRET_KEY:?};
      mc mb minioc/${S3_BUCKET_NAME:?};
      mc policy set public minioc/${S3_BUCKET_NAME:?};
      mc event add minioc/${S3_BUCKET_NAME:?} arn:minio:sqs::RABBIT:amqp --event put,delete;
      exit 0;
      "

  rabbit-external:
    image: rabbitmq:3.11.13-management-alpine
    ports:
    - "5672:5672"
    - "9002:15672"
    networks:
    - rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${GLOBAL_RABBIT_USERNAME:?}
      RABBITMQ_DEFAULT_PASS: ${GLOBAL_RABBIT_PASSWORD:?}
    healthcheck:
      test: [ CMD, curl, -f, http://localhost:15672 ]
      interval: 30s
      timeout: 10s
      retries: 5

  cache-db:
    ports:
    - "5432:5432"

  kafka:
    ports:
    - "9092:9092"

  service:
    build:
      context: .
    depends_on:
    - cache-db
    - kafka
    - rabbit-external
    - minio-external
    - minio-create-buckets
    - plugin-bigwig
    - plugin-biom
    - plugin-example
    - plugin-genelist
    - plugin-isasimple
    - plugin-rnaseq
    - plugin-wrangler
    links:
    - rabbit-external
    - minio-external
    networks:
    - rabbitmq
    ports:
    - "8080:${VDI_SERVICE_HTTP_PORT:-80}"
    environment:
      # NoOp Plugin
      PLUGIN_HANDLER_NOOP_NAME: ${PLUGIN_HANDLER_NOOP_NAME:?}
      PLUGIN_HANDLER_NOOP_DISPLAY_NAME: ${PLUGIN_HANDLER_NOOP_DISPLAY_NAME:?}
      PLUGIN_HANDLER_NOOP_VERSION: ${PLUGIN_HANDLER_NOOP_VERSION:?}
      PLUGIN_HANDLER_NOOP_ADDRESS: ${PLUGIN_HANDLER_NOOP_ADDRESS:?}
      PLUGIN_HANDLER_NOOP_PROJECT_IDS: ${PLUGIN_HANDLER_NOOP_PROJECT_IDS}


  plugin-example:
    image: veupathdb/vdi-plugin-example:${VDI_PLUGIN_EXAMPLE_TAG:-latest}
    networks:
      internal:
        aliases:
        - example
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_EXAMPLE_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH:?}
      target: ${DATASET_DIRECTORY_TARGET_PATH:?}
    environment:
      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}
      CUSTOM_PATH: ${PLUGIN_HANDLER_NOOP_CUSTOM_PATH}
      SITE_BUILD: ${SITE_BUILD:?}
      DATASET_INSTALL_ROOT: ${DATASET_DIRECTORY_TARGET_PATH:?}

      IMPORT_SCRIPT_MAX_DURATION: ${PLUGIN_HANDLER_NOOP_IMPORT_SCRIPT_MAX_DURATION}
      INSTALL_DATA_SCRIPT_MAX_DURATION: ${PLUGIN_HANDLER_NOOP_INSTALL_DATA_SCRIPT_MAX_DURATION}
      INSTALL_META_SCRIPT_MAX_DURATION: ${PLUGIN_HANDLER_NOOP_INSTALL_META_SCRIPT_MAX_DURATION}
      UNINSTALL_SCRIPT_MAX_DURATION: ${PLUGIN_HANDLER_NOOP_UNINSTALL_SCRIPT_MAX_DURATION}
      CHECK_COMPAT_SCRIPT_MAX_DURATION: ${PLUGIN_HANDLER_NOOP_CHECK_COMPAT_SCRIPT_MAX_DURATION}

      DB_CONNECTION_ENABLED_AMOEBA: ${DB_CONNECTION_ENABLED_AMOEBA}
      DB_CONNECTION_NAME_AMOEBA: ${DB_CONNECTION_NAME_AMOEBA:?}
      DB_CONNECTION_HOST_AMOEBA: ${DB_CONNECTION_HOST_AMOEBA}
      DB_CONNECTION_PORT_AMOEBA: ${DB_CONNECTION_PORT_AMOEBA}
      DB_CONNECTION_DB_NAME_AMOEBA: ${DB_CONNECTION_DB_NAME_AMOEBA}
      DB_CONNECTION_LDAP_AMOEBA: ${DB_CONNECTION_LDAP_AMOEBA}
      DB_CONNECTION_PASS_AMOEBA: ${DB_CONNECTION_PASS_AMOEBA:?}
      DB_CONNECTION_DATA_SCHEMA_AMOEBA: ${DB_CONNECTION_DATA_SCHEMA_AMOEBA:?}
      DB_CONNECTION_CONTROL_SCHEMA_AMOEBA: ${DB_CONNECTION_CONTROL_SCHEMA_AMOEBA:?}
      DB_CONNECTION_POOL_SIZE_AMOEBA: ${DB_CONNECTION_POOL_SIZE_AMOEBA}
      DB_CONNECTION_PLATFORM_AMOEBA: ${DB_CONNECTION_PLATFORM_AMOEBA}
      DB_CONNECTION_DATA_TYPES_AMOEBA: ${DB_CONNECTION_DATA_TYPES_AMOEBA}

      DB_CONNECTION_ENABLED_CRYPTO: ${DB_CONNECTION_ENABLED_CRYPTO}
      DB_CONNECTION_NAME_CRYPTO: ${DB_CONNECTION_NAME_CRYPTO:?}
      DB_CONNECTION_HOST_CRYPTO: ${DB_CONNECTION_HOST_CRYPTO}
      DB_CONNECTION_PORT_CRYPTO: ${DB_CONNECTION_PORT_CRYPTO}
      DB_CONNECTION_DB_NAME_CRYPTO: ${DB_CONNECTION_DB_NAME_CRYPTO}
      DB_CONNECTION_LDAP_CRYPTO: ${DB_CONNECTION_LDAP_CRYPTO}
      DB_CONNECTION_PASS_CRYPTO: ${DB_CONNECTION_PASS_CRYPTO:?}
      DB_CONNECTION_DATA_SCHEMA_CRYPTO: ${DB_CONNECTION_DATA_SCHEMA_CRYPTO:?}
      DB_CONNECTION_CONTROL_SCHEMA_CRYPTO: ${DB_CONNECTION_CONTROL_SCHEMA_CRYPTO:?}
      DB_CONNECTION_POOL_SIZE_CRYPTO: ${DB_CONNECTION_POOL_SIZE_CRYPTO}
      DB_CONNECTION_PLATFORM_CRYPTO: ${DB_CONNECTION_PLATFORM_CRYPTO}
      DB_CONNECTION_DATA_TYPES_CRYPTO: ${DB_CONNECTION_DATA_TYPES_CRYPTO}

      DB_CONNECTION_ENABLED_FUNGI: ${DB_CONNECTION_ENABLED_FUNGI}
      DB_CONNECTION_NAME_FUNGI: ${DB_CONNECTION_NAME_FUNGI:?}
      DB_CONNECTION_HOST_FUNGI: ${DB_CONNECTION_HOST_FUNGI}
      DB_CONNECTION_PORT_FUNGI: ${DB_CONNECTION_PORT_FUNGI}
      DB_CONNECTION_DB_NAME_FUNGI: ${DB_CONNECTION_DB_NAME_FUNGI}
      DB_CONNECTION_LDAP_FUNGI: ${DB_CONNECTION_LDAP_FUNGI}
      DB_CONNECTION_PASS_FUNGI: ${DB_CONNECTION_PASS_FUNGI:?}
      DB_CONNECTION_DATA_SCHEMA_FUNGI: ${DB_CONNECTION_DATA_SCHEMA_FUNGI:?}
      DB_CONNECTION_CONTROL_SCHEMA_FUNGI: ${DB_CONNECTION_CONTROL_SCHEMA_FUNGI:?}
      DB_CONNECTION_POOL_SIZE_FUNGI: ${DB_CONNECTION_POOL_SIZE_FUNGI}
      DB_CONNECTION_PLATFORM_FUNGI: ${DB_CONNECTION_PLATFORM_FUNGI}
      DB_CONNECTION_DATA_TYPES_FUNGI: ${DB_CONNECTION_DATA_TYPES_FUNGI}

      DB_CONNECTION_ENABLED_GIARDIA: ${DB_CONNECTION_ENABLED_GIARDIA}
      DB_CONNECTION_NAME_GIARDIA: ${DB_CONNECTION_NAME_GIARDIA:?}
      DB_CONNECTION_HOST_GIARDIA: ${DB_CONNECTION_HOST_GIARDIA}
      DB_CONNECTION_PORT_GIARDIA: ${DB_CONNECTION_PORT_GIARDIA}
      DB_CONNECTION_DB_NAME_GIARDIA: ${DB_CONNECTION_DB_NAME_GIARDIA}
      DB_CONNECTION_LDAP_GIARDIA: ${DB_CONNECTION_LDAP_GIARDIA}
      DB_CONNECTION_PASS_GIARDIA: ${DB_CONNECTION_PASS_GIARDIA:?}
      DB_CONNECTION_DATA_SCHEMA_GIARDIA: ${DB_CONNECTION_DATA_SCHEMA_GIARDIA:?}
      DB_CONNECTION_CONTROL_SCHEMA_GIARDIA: ${DB_CONNECTION_CONTROL_SCHEMA_GIARDIA:?}
      DB_CONNECTION_POOL_SIZE_GIARDIA: ${DB_CONNECTION_POOL_SIZE_GIARDIA}
      DB_CONNECTION_PLATFORM_GIARDIA: ${DB_CONNECTION_PLATFORM_GIARDIA}
      DB_CONNECTION_DATA_TYPES_GIARDIA: ${DB_CONNECTION_DATA_TYPES_GIARDIA}

      DB_CONNECTION_ENABLED_HOST: ${DB_CONNECTION_ENABLED_HOST}
      DB_CONNECTION_NAME_HOST: ${DB_CONNECTION_NAME_HOST:?}
      DB_CONNECTION_HOST_HOST: ${DB_CONNECTION_HOST_HOST}
      DB_CONNECTION_PORT_HOST: ${DB_CONNECTION_PORT_HOST}
      DB_CONNECTION_DB_NAME_HOST: ${DB_CONNECTION_DB_NAME_HOST}
      DB_CONNECTION_LDAP_HOST: ${DB_CONNECTION_LDAP_HOST}
      DB_CONNECTION_PASS_HOST: ${DB_CONNECTION_PASS_HOST:?}
      DB_CONNECTION_DATA_SCHEMA_HOST: ${DB_CONNECTION_DATA_SCHEMA_HOST:?}
      DB_CONNECTION_CONTROL_SCHEMA_HOST: ${DB_CONNECTION_CONTROL_SCHEMA_HOST:?}
      DB_CONNECTION_POOL_SIZE_HOST: ${DB_CONNECTION_POOL_SIZE_HOST}
      DB_CONNECTION_PLATFORM_HOST: ${DB_CONNECTION_PLATFORM_HOST}
      DB_CONNECTION_DATA_TYPES_HOST: ${DB_CONNECTION_DATA_TYPES_HOST}

      DB_CONNECTION_ENABLED_MICROSPORIDIA: ${DB_CONNECTION_ENABLED_MICROSPORIDIA}
      DB_CONNECTION_NAME_MICROSPORIDIA: ${DB_CONNECTION_NAME_MICROSPORIDIA:?}
      DB_CONNECTION_HOST_MICROSPORIDIA: ${DB_CONNECTION_HOST_MICROSPORIDIA}
      DB_CONNECTION_PORT_MICROSPORIDIA: ${DB_CONNECTION_PORT_MICROSPORIDIA}
      DB_CONNECTION_DB_NAME_MICROSPORIDIA: ${DB_CONNECTION_DB_NAME_MICROSPORIDIA}
      DB_CONNECTION_LDAP_MICROSPORIDIA: ${DB_CONNECTION_LDAP_MICROSPORIDIA}
      DB_CONNECTION_PASS_MICROSPORIDIA: ${DB_CONNECTION_PASS_MICROSPORIDIA:?}
      DB_CONNECTION_DATA_SCHEMA_MICROSPORIDIA: ${DB_CONNECTION_DATA_SCHEMA_MICROSPORIDIA:?}
      DB_CONNECTION_CONTROL_SCHEMA_MICROSPORIDIA: ${DB_CONNECTION_CONTROL_SCHEMA_MICROSPORIDIA:?}
      DB_CONNECTION_POOL_SIZE_MICROSPORIDIA: ${DB_CONNECTION_POOL_SIZE_MICROSPORIDIA}
      DB_CONNECTION_PLATFORM_MICROSPORIDIA: ${DB_CONNECTION_PLATFORM_MICROSPORIDIA}
      DB_CONNECTION_DATA_TYPES_MICROSPORIDIA: ${DB_CONNECTION_DATA_TYPES_MICROSPORIDIA}

      DB_CONNECTION_ENABLED_PIROPLASMA: ${DB_CONNECTION_ENABLED_PIROPLASMA}
      DB_CONNECTION_NAME_PIROPLASMA: ${DB_CONNECTION_NAME_PIROPLASMA:?}
      DB_CONNECTION_HOST_PIROPLASMA: ${DB_CONNECTION_HOST_PIROPLASMA}
      DB_CONNECTION_PORT_PIROPLASMA: ${DB_CONNECTION_PORT_PIROPLASMA}
      DB_CONNECTION_DB_NAME_PIROPLASMA: ${DB_CONNECTION_DB_NAME_PIROPLASMA}
      DB_CONNECTION_LDAP_PIROPLASMA: ${DB_CONNECTION_LDAP_PIROPLASMA}
      DB_CONNECTION_PASS_PIROPLASMA: ${DB_CONNECTION_PASS_PIROPLASMA:?}
      DB_CONNECTION_DATA_SCHEMA_PIROPLASMA: ${DB_CONNECTION_DATA_SCHEMA_PIROPLASMA:?}
      DB_CONNECTION_CONTROL_SCHEMA_PIROPLASMA: ${DB_CONNECTION_CONTROL_SCHEMA_PIROPLASMA:?}
      DB_CONNECTION_POOL_SIZE_PIROPLASMA: ${DB_CONNECTION_POOL_SIZE_PIROPLASMA}
      DB_CONNECTION_PLATFORM_PIROPLASMA: ${DB_CONNECTION_PLATFORM_PIROPLASMA}
      DB_CONNECTION_DATA_TYPES_PIROPLASMA: ${DB_CONNECTION_DATA_TYPES_PIROPLASMA}

      DB_CONNECTION_ENABLED_PLASMO: ${DB_CONNECTION_ENABLED_PLASMO}
      DB_CONNECTION_NAME_PLASMO: ${DB_CONNECTION_NAME_PLASMO:?}
      DB_CONNECTION_HOST_PLASMO: ${DB_CONNECTION_HOST_PLASMO}
      DB_CONNECTION_PORT_PLASMO: ${DB_CONNECTION_PORT_PLASMO}
      DB_CONNECTION_DB_NAME_PLASMO: ${DB_CONNECTION_DB_NAME_PLASMO}
      DB_CONNECTION_LDAP_PLASMO: ${DB_CONNECTION_LDAP_PLASMO}
      DB_CONNECTION_PASS_PLASMO: ${DB_CONNECTION_PASS_PLASMO:?}
      DB_CONNECTION_DATA_SCHEMA_PLASMO: ${DB_CONNECTION_DATA_SCHEMA_PLASMO:?}
      DB_CONNECTION_CONTROL_SCHEMA_PLASMO: ${DB_CONNECTION_CONTROL_SCHEMA_PLASMO:?}
      DB_CONNECTION_POOL_SIZE_PLASMO: ${DB_CONNECTION_POOL_SIZE_PLASMO}
      DB_CONNECTION_PLATFORM_PLASMO: ${DB_CONNECTION_PLATFORM_PLASMO}
      DB_CONNECTION_DATA_TYPES_PLASMO: ${DB_CONNECTION_DATA_TYPES_PLASMO}

      DB_CONNECTION_ENABLED_TOXO: ${DB_CONNECTION_ENABLED_TOXO}
      DB_CONNECTION_NAME_TOXO: ${DB_CONNECTION_NAME_TOXO:?}
      DB_CONNECTION_HOST_TOXO: ${DB_CONNECTION_HOST_TOXO}
      DB_CONNECTION_PORT_TOXO: ${DB_CONNECTION_PORT_TOXO}
      DB_CONNECTION_DB_NAME_TOXO: ${DB_CONNECTION_DB_NAME_TOXO}
      DB_CONNECTION_LDAP_TOXO: ${DB_CONNECTION_LDAP_TOXO}
      DB_CONNECTION_PASS_TOXO: ${DB_CONNECTION_PASS_TOXO:?}
      DB_CONNECTION_DATA_SCHEMA_TOXO: ${DB_CONNECTION_DATA_SCHEMA_TOXO:?}
      DB_CONNECTION_CONTROL_SCHEMA_TOXO: ${DB_CONNECTION_CONTROL_SCHEMA_TOXO:?}
      DB_CONNECTION_POOL_SIZE_TOXO: ${DB_CONNECTION_POOL_SIZE_TOXO}
      DB_CONNECTION_PLATFORM_TOXO: ${DB_CONNECTION_PLATFORM_TOXO}
      DB_CONNECTION_DATA_TYPES_TOXO: ${DB_CONNECTION_DATA_TYPES_TOXO}

      DB_CONNECTION_ENABLED_TRICH: ${DB_CONNECTION_ENABLED_TRICH}
      DB_CONNECTION_NAME_TRICH: ${DB_CONNECTION_NAME_TRICH:?}
      DB_CONNECTION_HOST_TRICH: ${DB_CONNECTION_HOST_TRICH}
      DB_CONNECTION_PORT_TRICH: ${DB_CONNECTION_PORT_TRICH}
      DB_CONNECTION_DB_NAME_TRICH: ${DB_CONNECTION_DB_NAME_TRICH}
      DB_CONNECTION_LDAP_TRICH: ${DB_CONNECTION_LDAP_TRICH}
      DB_CONNECTION_PASS_TRICH: ${DB_CONNECTION_PASS_TRICH:?}
      DB_CONNECTION_DATA_SCHEMA_TRICH: ${DB_CONNECTION_DATA_SCHEMA_TRICH:?}
      DB_CONNECTION_CONTROL_SCHEMA_TRICH: ${DB_CONNECTION_CONTROL_SCHEMA_TRICH:?}
      DB_CONNECTION_POOL_SIZE_TRICH: ${DB_CONNECTION_POOL_SIZE_TRICH}
      DB_CONNECTION_PLATFORM_TRICH: ${DB_CONNECTION_PLATFORM_TRICH}
      DB_CONNECTION_DATA_TYPES_TRICH: ${DB_CONNECTION_DATA_TYPES_TRICH}

      DB_CONNECTION_ENABLED_TRITRYP: ${DB_CONNECTION_ENABLED_TRITRYP}
      DB_CONNECTION_NAME_TRITRYP: ${DB_CONNECTION_NAME_TRITRYP:?}
      DB_CONNECTION_HOST_TRITRYP: ${DB_CONNECTION_HOST_TRITRYP}
      DB_CONNECTION_PORT_TRITRYP: ${DB_CONNECTION_PORT_TRITRYP}
      DB_CONNECTION_DB_NAME_TRITRYP: ${DB_CONNECTION_DB_NAME_TRITRYP}
      DB_CONNECTION_LDAP_TRITRYP: ${DB_CONNECTION_LDAP_TRITRYP}
      DB_CONNECTION_PASS_TRITRYP: ${DB_CONNECTION_PASS_TRITRYP:?}
      DB_CONNECTION_DATA_SCHEMA_TRITRYP: ${DB_CONNECTION_DATA_SCHEMA_TRITRYP:?}
      DB_CONNECTION_CONTROL_SCHEMA_TRITRYP: ${DB_CONNECTION_CONTROL_SCHEMA_TRITRYP:?}
      DB_CONNECTION_POOL_SIZE_TRITRYP: ${DB_CONNECTION_POOL_SIZE_TRITRYP}
      DB_CONNECTION_PLATFORM_TRITRYP: ${DB_CONNECTION_PLATFORM_TRITRYP}
      DB_CONNECTION_DATA_TYPES_TRITRYP: ${DB_CONNECTION_DATA_TYPES_TRITRYP}

      DB_CONNECTION_ENABLED_VECTOR: ${DB_CONNECTION_ENABLED_VECTOR}
      DB_CONNECTION_NAME_VECTOR: ${DB_CONNECTION_NAME_VECTOR:?}
      DB_CONNECTION_HOST_VECTOR: ${DB_CONNECTION_HOST_VECTOR}
      DB_CONNECTION_PORT_VECTOR: ${DB_CONNECTION_PORT_VECTOR}
      DB_CONNECTION_DB_NAME_VECTOR: ${DB_CONNECTION_DB_NAME_VECTOR}
      DB_CONNECTION_LDAP_VECTOR: ${DB_CONNECTION_LDAP_VECTOR}
      DB_CONNECTION_PASS_VECTOR: ${DB_CONNECTION_PASS_VECTOR:?}
      DB_CONNECTION_DATA_SCHEMA_VECTOR: ${DB_CONNECTION_DATA_SCHEMA_VECTOR:?}
      DB_CONNECTION_CONTROL_SCHEMA_VECTOR: ${DB_CONNECTION_CONTROL_SCHEMA_VECTOR:?}
      DB_CONNECTION_POOL_SIZE_VECTOR: ${DB_CONNECTION_POOL_SIZE_VECTOR}
      DB_CONNECTION_PLATFORM_VECTOR: ${DB_CONNECTION_PLATFORM_VECTOR}
      DB_CONNECTION_DATA_TYPES_VECTOR: ${DB_CONNECTION_DATA_TYPES_VECTOR}

      DB_CONNECTION_ENABLED_ORTHO: ${DB_CONNECTION_ENABLED_ORTHO}
      DB_CONNECTION_NAME_ORTHO: ${DB_CONNECTION_NAME_ORTHO:?}
      DB_CONNECTION_HOST_ORTHO: ${DB_CONNECTION_HOST_ORTHO}
      DB_CONNECTION_PORT_ORTHO: ${DB_CONNECTION_PORT_ORTHO}
      DB_CONNECTION_DB_NAME_ORTHO: ${DB_CONNECTION_DB_NAME_ORTHO}
      DB_CONNECTION_LDAP_ORTHO: ${DB_CONNECTION_LDAP_ORTHO}
      DB_CONNECTION_PASS_ORTHO: ${DB_CONNECTION_PASS_ORTHO:?}
      DB_CONNECTION_DATA_SCHEMA_ORTHO: ${DB_CONNECTION_DATA_SCHEMA_ORTHO:?}
      DB_CONNECTION_CONTROL_SCHEMA_ORTHO: ${DB_CONNECTION_CONTROL_SCHEMA_ORTHO:?}
      DB_CONNECTION_POOL_SIZE_ORTHO: ${DB_CONNECTION_POOL_SIZE_ORTHO}
      DB_CONNECTION_PLATFORM_ORTHO: ${DB_CONNECTION_PLATFORM_ORTHO}
      DB_CONNECTION_DATA_TYPES_ORTHO: ${DB_CONNECTION_DATA_TYPES_ORTHO}

      DB_CONNECTION_ENABLED_CLINEPI: ${DB_CONNECTION_ENABLED_CLINEPI}
      DB_CONNECTION_NAME_CLINEPI: ${DB_CONNECTION_NAME_CLINEPI:?}
      DB_CONNECTION_HOST_CLINEPI: ${DB_CONNECTION_HOST_CLINEPI}
      DB_CONNECTION_PORT_CLINEPI: ${DB_CONNECTION_PORT_CLINEPI}
      DB_CONNECTION_DB_NAME_CLINEPI: ${DB_CONNECTION_DB_NAME_CLINEPI}
      DB_CONNECTION_LDAP_CLINEPI: ${DB_CONNECTION_LDAP_CLINEPI}
      DB_CONNECTION_PASS_CLINEPI: ${DB_CONNECTION_PASS_CLINEPI:?}
      DB_CONNECTION_DATA_SCHEMA_CLINEPI: ${DB_CONNECTION_DATA_SCHEMA_CLINEPI:?}
      DB_CONNECTION_CONTROL_SCHEMA_CLINEPI: ${DB_CONNECTION_CONTROL_SCHEMA_CLINEPI:?}
      DB_CONNECTION_POOL_SIZE_CLINEPI: ${DB_CONNECTION_POOL_SIZE_CLINEPI}
      DB_CONNECTION_PLATFORM_CLINEPI: ${DB_CONNECTION_PLATFORM_CLINEPI}
      DB_CONNECTION_DATA_TYPES_CLINEPI: ${DB_CONNECTION_DATA_TYPES_CLINEPI}

      DB_CONNECTION_ENABLED_MICROBIOME: ${DB_CONNECTION_ENABLED_MICROBIOME}
      DB_CONNECTION_NAME_MICROBIOME: ${DB_CONNECTION_NAME_MICROBIOME:?}
      DB_CONNECTION_HOST_MICROBIOME: ${DB_CONNECTION_HOST_MICROBIOME}
      DB_CONNECTION_PORT_MICROBIOME: ${DB_CONNECTION_PORT_MICROBIOME}
      DB_CONNECTION_DB_NAME_MICROBIOME: ${DB_CONNECTION_DB_NAME_MICROBIOME}
      DB_CONNECTION_LDAP_MICROBIOME: ${DB_CONNECTION_LDAP_MICROBIOME}
      DB_CONNECTION_PASS_MICROBIOME: ${DB_CONNECTION_PASS_MICROBIOME:?}
      DB_CONNECTION_DATA_SCHEMA_MICROBIOME: ${DB_CONNECTION_DATA_SCHEMA_MICROBIOME:?}
      DB_CONNECTION_CONTROL_SCHEMA_MICROBIOME: ${DB_CONNECTION_CONTROL_SCHEMA_MICROBIOME:?}
      DB_CONNECTION_POOL_SIZE_MICROBIOME: ${DB_CONNECTION_POOL_SIZE_MICROBIOME}
      DB_CONNECTION_PLATFORM_MICROBIOME: ${DB_CONNECTION_PLATFORM_MICROBIOME}
      DB_CONNECTION_DATA_TYPES_MICROBIOME: ${DB_CONNECTION_DATA_TYPES_MICROBIOME}

      DB_CONNECTION_ENABLED_UNIDB: ${DB_CONNECTION_ENABLED_UNIDB}
      DB_CONNECTION_NAME_UNIDB: ${DB_CONNECTION_NAME_UNIDB:?}
      DB_CONNECTION_HOST_UNIDB: ${DB_CONNECTION_HOST_UNIDB}
      DB_CONNECTION_PORT_UNIDB: ${DB_CONNECTION_PORT_UNIDB}
      DB_CONNECTION_DB_NAME_UNIDB: ${DB_CONNECTION_DB_NAME_UNIDB}
      DB_CONNECTION_LDAP_UNIDB: ${DB_CONNECTION_LDAP_UNIDB}
      DB_CONNECTION_PASS_UNIDB: ${DB_CONNECTION_PASS_UNIDB:?}
      DB_CONNECTION_DATA_SCHEMA_UNIDB: ${DB_CONNECTION_DATA_SCHEMA_UNIDB:?}
      DB_CONNECTION_CONTROL_SCHEMA_UNIDB: ${DB_CONNECTION_CONTROL_SCHEMA_UNIDB:?}
      DB_CONNECTION_POOL_SIZE_UNIDB: ${DB_CONNECTION_POOL_SIZE_UNIDB}
      DB_CONNECTION_PLATFORM_UNIDB: ${DB_CONNECTION_PLATFORM_UNIDB}
      DB_CONNECTION_DATA_TYPES_UNIDB: ${DB_CONNECTION_DATA_TYPES_UNIDB}
