= VEuPathDB Dataset Installer Service (VDI)
:source-highlighter: highlightjs
:toc:

:confluence: https://veupathdb.atlassian.net/wiki/spaces

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifndef::env-github[]
:icons: font
endif::[]

== Links

=== Compose Stack & Configuration

[unstyled]
* https://github.com/VEuPathDB/vdi-compose-stack

=== Documentation

[unstyled]
* https://veupathdb.github.io/vdi-service/core/[HTTP API]
* https://veupathdb.github.io/vdi-service/schema/config/full-config.html[Full Stack Config]
* https://veupathdb.github.io/vdi-service/schema/config/plugin-config.html[Plugin Config]

=== Schema

JSON schema files for use with editor validation & autocomplete when editing
configuration files.

* https://veupathdb.github.io/vdi-service/schema/config/full-config.json[Service Stack Configuration Schema]
* https://veupathdb.github.io/vdi-service/schema/config/plugin-config.json[Plugin-Specific Configuration Schema] +
  (a subset of the full config schema)


== Development

=== Repository Structure

.Component Source
* link:project/conventions/[Gradle Build Conventions]
* link:project/common/[Shared Components]
** link:project/common/config/src/main/json/schema[Config File JSON Schema]
* link:project/core/[Core VDI Service Components]
** link:project/core/module/rest-service[REST Service]
** link:project/core/module/lane[Dataset Processing Lanes]
** link:project/core/module/daemon[Background Processes]
** link:project/core/lib/db/application[App DB Queries]
** link:project/core/lib/dataset/reconciler[Reconciler Core]
* link:project/plugin-server/[VDI Plugin Handler Server]
* link:stack-db/definition[Internal Cache DB DDL]


=== Building VDI Components

==== Docker Images

===== VDI Core Server

[source, shell]
----
make build-image
----

===== Internal Cache DB

[source, shell]
----
make build-db
----

==== Source Compilation

===== VDI Core Server

[source, shell]
----
make build-core-server
----

===== Regenerate RAML-Based Source

[source, shell]
----
make raml-gen
----

===== Plugin Server

[source, shell]
----
make raml-gen
----

=== Common Tasks

==== Release a New Version

The core service and plugin server are versioned together, however they are
presently built differently.

===== Plugin Server

When pushing up a new git tag, a
link:.github/workflows/plugin-server-release.yml[GitHub workflow] will
automatically be triggered to build and release the plugin server.  That
workflow will then open pull requests on each of the individual plugin
repositories to update their copies of the server to the newest version.

===== Core Server

The core server docker image build and push to DockerHub is handled in
https://ci.apidb.org/job/vdi-service/view/tags/[Jenkins].

==== Update Dependencies

Dependency version updates are automatically suggested once per week by
https://github.com/dependabot[GitHub's Dependabot], however if manual updates
are needed, the JVM dependencies for the full stack are declared in the
link:gradle/libs.versions.toml[dependency catalog]. +
(ref https://docs.gradle.org/current/userguide/version_catalogs.html[Gradle Version Catalogs])



== License

Copyright 2020 VEuPathDB

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License.  You may obtain a copy of the
License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied.  See the License for the
specific language governing permissions and limitations under the License.
