#%RAML 1.0 Library

uses:
  common: ../../common.raml

types:
  PluginListItem:
    displayName: Plugin Info
    additionalProperties: false
    properties:
      pluginName: string
      type: common.DatasetTypeOutput
      maxFileSize:
        type: integer
        format: int64
      allowedFileExtensions: string[]
      installTargets?:
        # language=markdown
        description: |-
          Projects that this plugin is restricted to.  An empty or absent list
          indicates that the plugin has no project restrictions and may be used
          on any site.
        type: common.InstallTargetID[]
