#%RAML 1.0 Library

types:
  VDI-ID:
    displayName: VDI ID
    description: Unique VDI identifier string.
    type: string
    minLength: 32
    maxLength: 32
    pattern: ^[0-9a-fA-F]{32}$

  User-ID:
    displayName: WDK User ID
    description: Unique user identifier
    type: integer
    format: int64
    minimum: 1
    maximum: 9223372036854775807

  AuthorizationKey:
    displayName: RPC Authorization Key
    description: |
      A token unique to an RPC action that allows the action to be run via an
      HTTP call.
    type: string
    minLength: 64
    maxLength: 64
    pattern: ^[0-9a-fA-F]{64}$

  ProjectID:
    displayName: Project ID
    description: |
      Name or ID of a target VEuPathDB project.
      
      Valid project IDs are:
      
      - AmoebaDB
      - CryptoDB
      - FungiDB
      - GiardiaDB
      - HostDB
      - MicrosporidiaDB
      - PiroplasmaDB
      - PlasmoDB
      - ToxoDB
      - TrichDB
      - TriTrypDB
      - VectorBase
      - VEuPathDB
    type: string
    example: PlasmoDB

  DeleteCleanupRequest:
    displayName: Delete Cleanup Request
    description: |
      Request for the service to clean up datasets that were soft deleted more
      than 24 hours prior to the request.
    type: object
    additionalProperties: false
    properties:
      authorization:
        type: AuthorizationKey
        required: true

  InstallCleanupRequest:
    displayName: Install Cleanup Request
    description: |
      Object controlling the install cleanup process and what datasets it should
      target.
      
      Requesters should specify one of the fields `all` or `targets` to control
      what datasets will be cleaned up.  If neither is specified the endpoint
      will do nothing.
    type: object
    additionalProperties: false
    properties:
      authorization:
        type: AuthorizationKey
        required: true
      all:
        type: boolean
        default: false
        required: false
      targets:
        type: array
        items:
          type: VDI-ID
        minItems: 1
        uniqueItems: true
        required: false

  DatasetShareOffer:
    displayName: Dataset Share Offer
    description: |
      An offer to share (or un-share) a dataset with a single target user.
    type: object
    additionalProperties: false
    properties:
      action:
        displayName: Offer Action
        description: |
          What action to take with the dataset share offer.
          
          Either `grant` or `revoke`.
          
          A value of `grant` means the share should be offered to the user
          if they do not already have the dataset, or continue to be
          allowed if they already have access to the dataset.
          
          A value of `revoke` means the share should not be offered to the
          target user if they do not already have the dataset, or the
          sharing should be stopped if the user did already have access to
          the dataset.
        type: string
        enum:
        - grant
        - revoke
        required: true

  DatasetShareReceipt:
    displayName: Dataset Share Receipt
    description: |
      A receipt or response to a share offer of a dataset to a single user.
    type: object
    additionalProperties: false
    properties:
      action:
        displayName: Acknowledgement Action
        description: |
          What action to take with acknowledging a dataset share offer.
          
          Either `accept` or `reject`.
          
          A value of `accept` means that the dataset that a share was
          offered for should become available to the accepting user.
          
          A value of `reject` means that the dataset that a share was
          offered for should become unavailable to the rejecting user.
        type: string
        enum:
        - accept
        - reject
        required: true

  DatasetDetails:
    displayName: Dataset Details
    description: |
      Details about a specific singular dataset.
    type: object
    additionalProperties: false
    properties:
      datasetID:
        type: VDI-ID
        required: true
      ownerID:
        type: User-ID
        required: true
      type:
        type: DatasetDetailsTypeInfo
        required: true
      meta:
        type: DatasetDetailsMeta
        required: false
        default: null
      status:
        type: DatasetStatusInfo
        required: true

  DatasetDetailsTypeInfo:
    displayName: Dataset Type Info
    description: Information about a specific dataset type.
    type: object
    additionalProperties: false
    properties:
      name:
        displayName: Type Name
        type: string
        required: true
      version:
        displayName: Type Version
        type: string
        required: true

  DatasetDetailsMeta:
    displayName: Dataset Meta Info
    description: User provided meta information about a dataset.
    type: object
    additionalProperties: false
    properties:
      name:
        displayName: Dataset Name
        type: string
        required: false
        default: null
      summary:
        displayName: Dataset Summary
        type: string
        required: false
        default: null
      description:
        displayName: Dataset Description
        type: string
        required: false
        default: null

  DatasetStatusInfo:
    displayName: Dataset Status Info
    description: Information about the import and install status of a dataset.
    type: object
    additionalProperties: false
    properties:
      import:
        type: DatasetImportStatus
        required: true
      install:
        type: DatasetInstallStatusEntry[]
        required: false
        default: null

  DatasetImportStatus:
    displayName: Dataset Import Status
    type: string
    enum:
    - awaiting-import
    - importing
    - imported
    - import-failed

  DatasetInstallStatus:
    displayName: Dataset Install Status
    type: string
    enum:
    - running
    - complete
    - failed
    - ready-for-reinstall

  DatasetInstallStatusEntry:
    displayName: Dataset Install Status Entry
    description: Entry in a list of install statuses for a dataset.
    type: object
    additionalProperties: false
    properties:
      projectID:
        type: ProjectID
        required: true
      status:
        type: DatasetInstallStatus
        required: true

  DatasetListEntry:
    displayName: Dataset List Item
    description: Short entry with basic details about a dataset.
    type: object
    additionalProperties: false
    properties:
      datasetID:
        type: VDI-ID
        required: true
      ownerID:
        type: User-ID
        required: true
      type:
        type: DatasetDetailsTypeInfo
        required: true
      meta:
        type: DatasetDetailsMeta
        required: false
        default: null
      status:
        type: DatasetStatusInfo
        required: true

  DatasetPostRequest:
    displayName: Dataset Upload Post Request
    description: |
      Dataset upload post request body.
      
      This request body contains a JSON blob with details about the dataset
      being uploaded in addition to the files that make up the dataset.
    type: object
    additionalProperties: true
    properties:
      details:
        type: DatasetPostRequestDetails
        required: true

  DatasetPostRequestDetails:
    displayName: Dataset Upload Details
    description: Details about a dataset being uploaded.
    type: object
    additionalProperties: false
    properties:
      meta:
        type: DatasetDetailsMeta
        required: false
        default: null

  DatasetPostResponse:
    displayName: Dataset Upload Response
    description: |
      Response object returned on successful upload of a dataset.
      
      Note that the dataset being uploaded is not the same as the dataset being
      imported.  The importing of a dataset happens asynchronously at some point
      after the dataset is uploaded.
    type: object
    additionalProperties: false
    properties:
      datasetID:
        type: VDI-ID
        required: true