#%RAML 1.0 Resource

displayName: Open Dataset Share Offers

get:
  displayName: List Offers
  description: |
    Endpoint to list dataset shares that have been offered to the requesting
    user.

  queryParameters:
    status:
      displayName: Share Status
      description: |
        Controls the results by filtering them to only shares that are in the
        specified target status.

        Valid `status` values are:

        - `open`
        - `accepted`
        - `rejected`
        - `all`

        These status values mean:

        <table>
          <tr>
            <th>Status</th>
            <th>Description</th>
          </tr>
          <tr>
            <td>`open`</td>
            <td>Only return share offers that have not yet been accepted or
                rejected.</td>
          </tr>
          <tr>
            <td>`accepted`</td>
            <td>Only return share offers that have been accepted by the          
                requesting user.</td>
          </tr>
          <tr>
            <td>`rejected`</td>
            <td>Only return share offers that have been rejected by the
                requesting user.</td>
          </tr>
          <tr>
            <td>`all`</td>
            <td>Return all share offers regardless of whether they have been
                acknowledged, accepted, or rejected.</td>
          </tr>
        </table>
      type: string
      required: false
      default: open

  responses:
    200:
      body: lib.ShareOfferEntry[]
    400:
      body: lib.BadRequestError
    401:
      body: lib.UnauthorizedError
    500:
      body: lib.ServerError
