#%RAML 1.0 Library

uses:
  common: ../../../../common.raml

types:
  UserMetadata:
    displayName: User Details
    additionalProperties: false
    properties:
      quota: UserQuotaDetails

  UserQuotaDetails:
    displayName: User Quota Report
    additionalProperties: false
    properties:
      limit:
        description: Max number of bytes a user is allowed to upload.
        type: integer
        format: int64
      usage:
        description: Current number of bytes counted against the user's quota.
        type: integer
        format: int64
