name: API Doc Builder Tasks
description: Builds VDI API docs for publishing in GitHub pages.

inputs:
  output-dir:
    description: Document output directory.
    required: true
  ref:
    description: Git ref
    required: true
  gh-token:
    description: GitHub token
    required: true
  gh-user:
    description: GitHub username.
    required: true

runs:
  using: composite
  env:
    SCHEMA_PROJECT_DIR: project/common/config

  steps:
  - name: Ensure Workspace Dirs
    shell: bash
    run: mkdir -p ${{ inputs.output-dir }}/schema/config

  - name: Checkout Ref "${{ inputs.ref }}"
    uses: actions/checkout@v4
    with:
      clean: false
      ref: '${{ inputs.ref }}'

  - name: Compile RAML Docs
    shell: bash
    run: gradle :generate-raml-docs
    env:
      GITHUB_USERNAME: ${{ inputs.gh-user }}
      GITHUB_TOKEN: ${{ inputs.gh-token }}

  - name: Compile Service Config Schema
    shell: bash
    run: gradle :commons:config:compile-config-schema
    env:
      GITHUB_USERNAME: ${{ inputs.gh-user }}
      GITHUB_TOKEN: ${{ inputs.gh-token }}

  - name: Copy Gradle Outputs
    shell: bash
    run: >-
      cp -rt ${{ inputs.output-dir }} \
        docs/vdi-api.html \
        ${{ env.SCHEMA_PROJECT_DIR }}/build/json-schema/*
      cp -rt ${{ inputs.output-dir }}/schema \
        ${{ env.SCHEMA_PROJECT_DIR }}/src/main/json/schema/config/core-config.json

  - name: Compile Config Schema Docs
    shell: bash
    run: >-
      generate-schema-doc \
        --config expand_buttons \
        --config examples_as_yaml \
        --config no_link_to_reused_ref \
        ${{ env.SCHEMA_PROJECT_DIR }}/src/main/json/schema/config/core-config.json \
        ${{ inputs.output-dir }}/config-schema.html

