name: API Doc Builder Tasks
description: Builds VDI API docs for publishing in GitHub pages.

inputs:
  output-dir:
    description: Document output directory.
    required: true
  ref:
    description: Git ref
    required: true
  gh-token:
    description: GitHub token
    required: true
  gh-user:
    description: GitHub username.
    required: true

runs:
  using: composite
  steps:
  - name: Ensure Workspace Dirs
    shell: bash
    run: mkdir -p ${{ inputs.output-dir }}/schema/data ${{ inputs.output-dir }}/schema/config

  - name: Checkout Ref "${{ inputs.ref }}"
    uses: actions/checkout@v4
    with:
      clean: false
      ref: '${{ inputs.ref }}'

  - name: Compile RAML Docs
    shell: bash
    run: gradle :service:generate-raml-docs
    env:
      GITHUB_USERNAME: ${{ inputs.gh-user }}
      GITHUB_TOKEN: ${{ inputs.gh-token }}

  - name: Compile Dataset Characteristics Schema
    shell: bash
    run: gradle :service:schema:build-dataset-schema-resources
    env:
      GITHUB_USERNAME: ${{ inputs.gh-user }}
      GITHUB_TOKEN: ${{ inputs.gh-token }}

  - name: Compile Service Config Schema
    shell: bash
    run: gradle :service:schema:build-config-schema-resource
    env:
      GITHUB_USERNAME: ${{ inputs.gh-user }}
      GITHUB_TOKEN: ${{ inputs.gh-token }}

  - name: Copy Gradle Outputs
    shell: bash
    run: >-
      cp -rt ${{ inputs.output-dir }}
        docs/vdi-api.html
        service/schema
        service/schema/build/json-schema/*

  - name: Compile Config Schema Docs
    shell: bash
    run: >-
      generate-schema-doc
        --config expand_buttons
        --config examples_as_yaml
        --config no_link_to_reused_ref
        service/schema/config/stack-config.json
        ${{ inputs.output-dir }}/config-schema.html

