#%RAML 1.0

title: VEuPathDB Dataset Handler Server
version: 1.0.0
mediaType: application/json
description: |
  HTTP API for the VDI Handler Plugin Server.
  
  The VDI Handler Plugin Server is a small HTTP server that collects, organizes,
  and wraps calls to VDI import and install scripts, allowing them to be
  executed via HTTP calls.
  
  Every endpoint declared as part of this API is backed by a shell or system
  call to a "plugin" script being hosted in the same container as this util
  server.

/import-processing/{vdi-id}:
  displayName: Import Actions

  uriParameters:
    vdi-id: VDI-ID

  post:
    displayName: Perform Import Processing
    description: |
      Perform dataset validation and any pre-installation transformation that
      needs to be done.
      
      The output of this endpoint is a tarball containing the processing result
      files that are ready to be imported into the VDI Dataset Store (MinIO at
      the time of this writing)
      
      **Note**: The definition of the request body below appears no differently
      than if it were defining a JSON object to be posted, however, it is
      instead defining fields that are part of a `multipart/form-data` request.
      This means that the properties defined as part of the root "object" are
      actually fields in the multipart request.
    body:
      multipart/form-data:
        type: DatasetMultipartPostBody

    responses:
      200:
        description: |
          Success
          
          Server has successfully processed the dataset for import and is
          returning the result.
        body:
          application/octet-stream:
            type: file

      400:
        description: |
          Malformed Request
          
          The request body was malformed in a way that prevented the server from
          parsing it.
        body:
          application/json:
            type: BadRequestResponse

      422:
        description: |
          Dataset Validation Failure
          
          The provided dataset failed the import validation portion of the
          dataset processing.

        body:
          application/json:
            type: ValidationFailureResponse

      500:
        description: |
          Internal Server Error
          
          Congratulations!  You found a bug!
        body:
          application/json:
            type: InternalServerErrorResponse


/install/{vdi-id}:
  displayName: Install Actions

  uriParameters:
    vdi-id: VDI-ID

  /meta:
    displayName: Install Dataset Meta

    post:
      body:
        application/json:
          type: DatasetMeta
      responses:
        204:
          description: |
            Success
            
            The metadata for the dataset was successfully installed into the
            target application database.

        400:
          description: |
            Bad Request
            
            The request body was malformed.
          body:
            application/json:
              type: BadRequestResponse

        500:
          description: |
            Internal Server Error
            
            Congratulations!  You found a bug!
          body:
            application/json:
              type: InternalServerErrorResponse

  /data:
    displayName: Install Dataset Data

    post:

      body:
        application/json:
          type: DatasetMultipartPostBody

      responses:

        200:
          description: Success
          body:
            application/json:
              type: DatasetInstallationResponse

        400:
          description: Validation Error
          body:
            application/json:
              type: BadRequestResponse

        418:
          description: Installation Error?
          body:
            application/json:

        500:
          description: Internal Server Error
          body:
            application/json:
              type: InternalServerErrorResponse


/delete/{vdi-id}:
  displayName: Delete Actions

  uriParameters:
    vdi-id: VDI-ID
  post:
    displayName: Delete Dataset
    responses:
      204:
      500:
        description: Internal Server Error
        body:
          application/json:
            type: InternalServerErrorResponse

/update/{vdi-id}:
  displayName: Update Actions

  uriParameters:
    vdi-id: VDI-ID

  /meta:
    post:
      displayName: Update Dataset Meta
      body:
        application/json:
          type: DatasetMeta
      responses:
        204:
        400:
          description: Malformed Request
          body:
            application/json:
              type: BadRequestResponse
        422:
          description: Request Validation Error
          body:
            application/json:
              type: ValidationFailureResponse
        500:
          description: Internal Server Error
          body:
            application/json:
              type: InternalServerErrorResponse

types:
  VDI-ID:
    displayName: VDI ID
    description: Unique VDI Dataset identifier string.
    type: string
    minLength: 32
    maxLength: 32
    pattern: ^[0-9a-fA-F]{32}$
    example: 78609580dba2787a5cf677d6f334a707

  User-ID:
    displayName: VEuPathDB User ID
    description: Unique user identifier
    type: integer
    format: int64
    minimum: 1
    maximum: 9223372036854775807
    example: 204435

  ProjectID:
    displayName: Project ID
    description: |
      Name or ID of a target VEuPathDB project.

      Valid project IDs are:

      - AmoebaDB
      - CryptoDB
      - FungiDB
      - GiardiaDB
      - HostDB
      - MicrosporidiaDB
      - PiroplasmaDB
      - PlasmoDB
      - ToxoDB
      - TrichDB
      - TriTrypDB
      - VectorBase
      - VEuPathDB
    type: string
    example: PlasmoDB

  DatasetMultipartPostBody:
    type: object
    properties:
      manifest:
        type: DatasetManifest
        required: true
      meta:
        type: DatasetMeta
        required: true
      /^.+$/:
        type: file
    minProperties: 3

  DatasetManifest:
    type: object
    additionalProperties: false
    properties:
      dataFiles:
        type: DatasetManifestDataFileEntry[]
        required: true

  DatasetManifestDataFileEntry:
    type: object
    additionalProperties: false
    properties:
      name:
        type: string
        required: true
      path:
        type: string
        required: true

  DatasetMeta:
    type: object
    additionalProperties: false
    properties:
      type:
        type: DatasetMetaType
        required: true
      projects:
        type: ProjectID[]
        required: true
        minItems: 1
      owner:
        type: User-ID
        required: true
      name:
        type: string
        required: true
      summary:
        type: string
        required: true
      description:
        type: string
        required: true
      dependencies:
        type: DatasetMetaDependency[]
        required: true

  DatasetMetaType:
    type: object
    additionalProperties: false
    properties:
      name:
        type: string
        required: true
      version:
        type: string
        required: true

  DatasetMetaDependency:
    type: object
    additionalProperties: false
    properties:
      resourceIdentifier:
        type: any
        required: true
      resourceVersion:
        type: any
        required: true
      resourceDisplayName:
        type: any
        required: true

  DatasetInstallationResponse:
    type: object
    additionalProperties: false
    properties:
      warnings:
        type: string[]
        required: false
        default: []

  ValidationFailureResponse:
    type: object
    additionalProperties: false
    properties:
      general:
        type: string[]
        required: false
        default: []
      keyed:
        type: object
        properties:
          /^.+$/:
            type: string[]
        required: false
        default: {}

  BadRequestResponse:
    type: object
    additionalProperties: false
    properties:
      message:
        type: string
        required: true

  InternalServerErrorResponse:
    type: object
    additionalProperties: false
    properties:
      message:
        type: string
        required: true