#!/usr/bin/env bash

set -m

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Make sure K8S is running
sudo microk8s start

# Enable the features we need
sudo microk8s enable rbac
sudo microk8s enable dashboard
sudo microk8s enable dns

# Create our VDI namespace (deleting any previous junk left over first)
microk8s kubectl delete namespace vdi
microk8s kubectl create namespace vdi

# Get the IP of our gateway (we're not actually using docker, we just need an
# "external" handle on localhost)
externalIP="$(ip route | grep docker | cut -d' ' -f9)"

# Create a kubernetes endpoint from which we can access the external vault
# instance
microk8s kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Service
metadata:
  name: external-vault
  namespace: vdi
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-vault
  namespace: vdi
subsets:
  - addresses:
      - ip: $externalIP
    ports:
      - port: 8200
EOF

# Create a service account for VDI
microk8s kubectl create sa -n vdi vdi

# Create an auth token for our service account (the token value is automatically
# generated by K8S)
microk8s kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: vault-token-g955r
  namespace: vdi
  annotations:
    kubernetes.io/service-account.name: vdi
type: kubernetes.io/service-account-token
EOF

# Start up vault
vault server -dev -dev-root-token-id root -dev-listen-address 0.0.0.0:8200 &

export VAULT_ADDR='http://0.0.0.0:8200'

# Login to vault
vault login root

# Enable Vault's Kubernetes authentication
vault auth enable kubernetes

# Write the kv secrets to vault
$SCRIPT_DIR/vault-write-secrets.sh

# Fetch the details needed to set up the kubernetes auth config
TOKEN_REVIEW_JWT=$(microk8s kubectl get secret vault-token-g955r -n vdi --output='go-template={{ .data.token }}' | base64 --decode)
KUBE_HOST=$(microk8s kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.server}')
KUBE_CA_CERT=$(microk8s kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.certificate-authority-data}' | base64 --decode)

# Setup the kubernetes auth config
vault write auth/kubernetes/config \
  token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
  kubernetes_host="$KUBE_HOST" \
  kubernetes_ca_cert="$KUBE_CA_CERT" \
  issuer="https://kubernetes.default.svc.cluster.local"

# Create a role for VDI
vault write auth/kubernetes/role/vdi \
  bound_service_account_names=vdi \
  bound_service_account_namespaces=vdi \
  policies=vdi \
  ttl=24h

fg