#%RAML 1.0 Library

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.3.0/libraries/errors.raml

types:
  DatasetCategory:
    type: string
    maxLength: 100

  DatasetContact:
    additionalProperties: false
    properties:
      name:
        type: string
        minLength: 3
        maxLength: 300
      email?:
        type: string
        minLength: 5
        maxLength: 4000
      affiliation?:
        type: string
        maxLength: 4000
      city?:
        type: string
        maxLength: 200
      state?:
        type: string
        maxLength: 200
      country?:
        type: string
        maxLength: 200
      address?:
        type: string
        maxLength: 1000
      isPrimary?:
        type: boolean
        default: false

  DatasetCreationDate:
    description: Timestamp of the creation of the dataset
    type: datetime

  DatasetDependency:
    additionalProperties: false
    properties:
      resourceIdentifier: string
      resourceDisplayName: string
      resourceVersion: string

  DatasetDescription:
    type: string
    description: Longform description of the dataset.

  DatasetHyperlink:
    type: object
    additionalProperties: false
    properties:
      url:
        type: string
        minLength: 3
        maxLength: 200
      text:
        type: string
        minLength: 3
        maxLength: 300
      description?:
        type: string
        maxLength: 4000
      isPublication?:
        type: boolean
        default: false

  DatasetImportStatus:
    description: |
      Import status of the dataset.

      | Value         | Description                                                           |
      |---------------|-----------------------------------------------------------------------|
      | `queued`      | The dataset has not yet been processed and is waiting in the queue.   |
      | `in-progress` | The dataset is currently being import processed.                      |
      | `complete`    | The dataset has been processed and imported for installation.         |
      | `invalid`     | The dataset failed import validation.                                 |
      | `failed`      | The dataset import failed due to an internal server error.            |

    type: string
    enum:
    - queued
    - in-progress
    - complete
    - invalid
    - failed

  DatasetInstallStatus:
    type: string
    enum:
    - running
    - complete
    - failed-validation
    - failed-installation
    - ready-for-reinstall
    - missing-dependency

  DatasetInstallStatusEntry:
    description: Entry in a list of install statuses for a dataset.
    additionalProperties: false
    properties:
      projectId: ProjectId
      metaStatus: DatasetInstallStatus
      metaMessage?: string
      dataStatus?: DatasetInstallStatus
      dataMessage?: string

  DatasetName:
    type: string
    description: User-provided name for the dataset.

  DatasetOrigin:
    description: |
      String representing the origin of the dataset.  Examples include
      `direct-upload`, `nephele`, or `galaxy`.
    type: string

  DatasetOwner:
    description: Details about the owner of a VDI dataset.
    additionalProperties: false
    properties:
      userId: UserId
      firstName?: string
      lastName?: string
      email?: string
      organization?: string

  DatasetPublication:
    additionalProperties: false
    properties:
      pubMedId:
        type: string
        minLength: 3
        maxLength: 30
      citation?:
        type: string
        minLength: 3
        maxLength: 2000

  DatasetShortAttribution:
    type: string
    maxLength: 300

  DatasetShortName:
    type: string
    maxLength: 300

  DatasetSourceUrl:
    description: |
      URL of the dataset data source, if the dataset was uploaded via URL.
    type: string

  DatasetStatusInfo:
    description: Information about the import and install status of a dataset.
    additionalProperties: false
    properties:
      import: DatasetImportStatus
      install?: DatasetInstallStatusEntry[]

  DatasetSummary:
    description: Brief summary of the dataset.
    type: string
    maxLength: 4000

  DatasetTypeInfo:
    description: Details about a specific dataset type.
    additionalProperties: false
    properties:
      name: string
      version: string
      displayName?:
        description: |
          Display name for the type.  This field is ignored in requests and will
          always be present in responses.
        type: string

  DatasetVisibility:
    type: string
    enum:
    - private
    - protected
    - public

  ProjectId:
    description: |
      Name or ID of a target VEuPathDB project.

      Valid project IDs are:

      - AmoebaDB
      - ClinEpiDB
      - CryptoDB
      - FungiDB
      - GiardiaDB
      - HostDB
      - MicrobiomeDB
      - MicrosporidiaDB
      - PiroplasmaDB
      - PlasmoDB
      - ToxoDB
      - TrichDB
      - TriTrypDB
      - VectorBase
      - VEuPathDB
    type: string

  ShareOfferAction:
    type: string
    enum:
    - grant
    - revoke

  ShareReceiptAction:
    type: string
    enum:
    - accept
    - reject

  UserId:
    description: VEuPathDB User ID
    type: integer
    format: int64
    minimum: 1
    maximum: 9223372036854775807

  VdiId:
    description: VDI dataset identifier
    type: string
    pattern: ^[a-zA-Z0-9_-]+$
