#%RAML 1.0 Resource

displayName: Users

/self:
  displayName: Current User

  /meta:
    displayName: Metadata
    get:
      description: Get user metadata.
      responses:
        200:
          body: lib.UserMetadata
        401:
          body: lib.UnauthorizedError
        500:
          body: lib.ServerError

  /share-offers: !include self/share-offers/resource.raml
