package vdi

object Consts {
  const val IMPORT_SCRIPT_EXIT_SUCCESS_CODE             = 0
  const val IMPORT_SCRIPT_EXIT_FAIL_VALIDATION_CODE     = 1
  const val IMPORT_SCRIPT_EXIT_FAIL_TRANSFORMATION_CODE = 2
  const val IMPORT_SCRIPT_EXIT_FAIL_UNEXPECTED_CODE     = 3

  //
  //
  // Configuration Defaults
  //
  //

  const val DEFAULT_SERVER_PORT = "80"
  const val DEFAULT_SERVER_HOST = "0.0.0.0"

  const val DEFAULT_IMPORT_SCRIPT_PATH       = "/opt/veupathdb/import"
  const val DEFAULT_DATA_INSTALL_SCRIPT_PATH = "/opt/veupathdb/install-data"
  const val DEFAULT_META_INSTALL_SCRIPT_PATH = "/opt/veupathdb/install-meta"
  const val DEFAULT_UNINSTALL_SCRIPT_PATH    = "/opt/veupathdb/uninstall"

  const val DEFAULT_IMPORT_SCRIPT_MAX_DURATION       = "1h"
  const val DEFAULT_INSTALL_DATA_SCRIPT_MAX_DURATION = "1h"
  const val DEFAULT_INSTALL_META_SCRIPT_MAX_DURATION = "1h"
  const val DEFAULT_UNINSTALL_SCRIPT_MAX_DURATION    = "1h"

  //
  //
  // Service Configuration Environment Variables
  //
  //
  const val ENV_IMPORT_SCRIPT_PATH = "IMPORT_SCRIPT_PATH"
  const val ENV_IMPORT_SCRIPT_MAX_DURATION = "IMPORT_SCRIPT_MAX_DURATION"

  const val ENV_INSTALL_DATA_SCRIPT_PATH = "INSTALL_DATA_SCRIPT_PATH"
  const val ENV_INSTALL_DATA_SCRIPT_MAX_DURATION = "INSTALL_DATA_SCRIPT_MAX_DURATION"

  const val ENV_INSTALL_META_SCRIPT_PATH = "INSTALL_META_SCRIPT_PATH"
  const val ENV_INSTALL_META_SCRIPT_MAX_DURATION = "INSTALL_META_SCRIPT_MAX_DURATION"

  const val ENV_UNINSTALL_SCRIPT_PATH = "UNINSTALL_SCRIPT_PATH"
  const val ENV_UNINSTALL_SCRIPT_MAX_DURATION = "UNINSTALL_SCRIPT_MAX_DURATION"

  const val ENV_SERVER_PORT = "SERVER_PORT"
  const val ENV_SERVER_HOST = "SERVER_HOST"
}