apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test
spec:
  containers:
  - name: test-container
    image: alpine:3.21.3
    envFrom:
    - secretRef:
        name: test-secret
    command:
    - sh
    - -c
    - 'echo $SECRET; sleep 10000'
