$schema: https://veupathdb.github.io/vdi-service/schema/config/stack-config.json

definitions:
  genomicsProjects: &genomicsProjects
  - AmoebaDB
  - CryptoDB
  - FungiDB
  - GiardiaDB
  - HostDB
  - MicrosporidiaDB
  - PiroplasmaDB
  - PlasmoDB
  - ToxoDB
  - TrichDB
  - TriTrypDB
  - VectorBase
  - VEuPathDB
  datasetPropertiesJsonSchemaFiles:
  - &genDatasetProps /schema/data/dataset-characteristics.genomics.json
  - &edaDatasetProps /schema/data/dataset-characteristics.eda.json

containerCore:
  authentication:
    oauth:
      clientId: ${env:OAUTH_CLIENT_ID}
      clientSecret: ${env:OAUTH_CLIENT_SECRET}
      url: ${env:OAUTH_URL:-https://eupathdb.org/oauth}
      keystoreFile: ${env:KEY_STORE_FILE:-""}
      keystorePass: ${env:KEY_STORE_PASS_PHRASE:-""}
    adminToken: ${env:ADMIN_AUTH_TOKEN}
  http:
    bindPort: ${env:VDI_SERVICE_HTTP_PORT:-80}
    enableCors: ${env:ENABLE_CORS:-false}

vdi:
  siteBuild: ${env:SITE_BUILD:-build-68}

  ldap:
    servers: ${env:LDAP_SERVER}
    baseDn: ${env:ORACLE_BASE_DN}

  objectStore:
    bucketName: ${env:S3_BUCKET_NAME}
    server: ${env:S3_HOST}:${env:S3_PORT:-9000}
    https: ${env:S3_USE_HTTPS:-true}
    accessToken: ${env:S3_ACCESS_TOKEN}
    secretKey: ${env:S3_SECRET_KEY}

  restService:
    enableJerseyTrace: ${env:ENABLE_JERSEY_TRACE:-false}

  daemons:
    reconciler:
      enabled: false

  rabbit:
    global:
      connection:
        server:
          host: ${env:GLOBAL_RABBIT_HOST}
          port: ${env:GLOBAL_RABBIT_PORT:-5672}
        username: ${env:GLOBAL_RABBIT_USERNAME}
        password: ${env:GLOBAL_RABBIT_PASSWORD}
        tls: ${env:GLOBAL_RABBIT_USE_TLS:-true}
      exchange:
        name: ${env:GLOBAL_RABBIT_VDI_EXCHANGE_NAME:-vdi-bucket-notifications}
      queue:
        name: ${env:GLOBAL_RABBIT_VDI_QUEUE_NAME:-vdi-bucket-notifications}
      routing:
        key: ${env:GLOBAL_RABBIT_VDI_ROUTING_KEY:-vdi-bucket-notifications}

  kafka:
    servers:
    - ${env:KAFKA_SERVERS:-kafka:9092}

  cacheDb:
    username: ${env:CACHE_DB_USERNAME:-vdi}
    password: ${env:CACHE_DB_PASSWORD}
    server: ${env:CACHE_DB_HOST:-cache-db}:${env:CACHE_DB_PORT:-5432}

  plugins:
  - server: ${env:PLUGIN_HANDLER_BIGWIG_ADDRESS:-bigwig:80}
    displayName: ${env:PLUGIN_HANDLER_BIGWIG_DISPLAY_NAME:-bigWig}
    dataTypes:
    - name: ${env:PLUGIN_HANDLER_BIGWIG_NAME:-bigwigfiles}
      version: ${env:PLUGIN_HANDLER_BIGWIG_VERSION:-1.0}
    projectIds: *genomicsProjects

  - server: ${env:PLUGIN_HANDLER_BIOM_ADDRESS:-biom:80}
    displayName: ${env:PLUGIN_HANDLER_BIOM_DISPLAY_NAME:-BIOM}
    dataTypes:
    - name: ${env:PLUGIN_HANDLER_BIOM_NAME:-biom}
      version: ${env:PLUGIN_HANDLER_BIOM_VERSION:-1.0}
    projectIds:
    - MicrobiomeDB

  - server: ${env:PLUGIN_HANDLER_GENELIST_ADDRESS:-genelist:80}
    displayName: ${env:PLUGIN_HANDLER_GENELIST_DISPLAY_NAME:-Gene List}
    dataTypes:
    - name: ${env:PLUGIN_HANDLER_GENELIST_NAME:-genelist}
      version: ${env:PLUGIN_HANDLER_GENELIST_VERSION:-1.0}
    projectIds: *genomicsProjects

  - server: ${env:PLUGIN_HANDLER_ISASIMPLE_ADDRESS:-isasimple:80}
    displayName: ${env:PLUGIN_HANDLER_ISASIMPLE_DISPLAY_NAME:-ISA Study}
    dataTypes:
    - name: ${env:PLUGIN_HANDLER_ISASIMPLE_NAME:-isasimple}
      version: ${env:PLUGIN_HANDLER_ISASIMPLE_VERSION:-1.0}
    projectIds:
    - ClinEpiDB

  - server: ${env:PLUGIN_HANDLER_NOOP_ADDRESS:-noop:80}
    displayName: ${env:PLUGIN_HANDLER_NOOP_DISPLAY_NAME:-Lightweight}
    dataTypes:
    - name: ${env:PLUGIN_HANDLER_NOOP_NAME:-lightweight}
      version: ${env:PLUGIN_HANDLER_NOOP_VERSION:-1.0}
    typeChangesEnabled: true

  - server: phenotype:80
    displayName: Phenotype
    dataTypes:
    - name: phenotype
      version: 1.0
    projectIds: *genomicsProjects

  - server: ${env:PLUGIN_HANDLER_RNASEQ_ADDRESS:-rnaseq:80}
    displayName: ${env:PLUGIN_HANDLER_RNASEQ_DISPLAY_NAME:-RNA-seq}
    dataTypes:
    - name: ${env:PLUGIN_HANDLER_RNASEQ_NAME:-rnaseq}
      version: ${env:PLUGIN_HANDLER_RNASEQ_VERSION:-1.0}
    projectIds: *genomicsProjects

  installTargets:
  - targetName: ${env:DB_CONNECTION_NAME_AMOEBA:-AmoebaDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_AMOEBA}
      password: ${env:DB_CONNECTION_PASS_AMOEBA}
      lookupCn: ${env:DB_CONNECTION_LDAP_AMOEBA}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_AMOEBA}
      password: ${env:DB_CONNECTION_PASS_AMOEBA}
      lookupCn: ${env:DB_CONNECTION_LDAP_AMOEBA}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_AMOEBA:-true}

  - targetName: ${env:DB_CONNECTION_NAME_CLINEPI:-ClinEpiDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_CLINEPI}
      password: ${env:DB_CONNECTION_PASS_CLINEPI}
      lookupCn: ${env:DB_CONNECTION_LDAP_CLINEPI}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_CLINEPI}
      password: ${env:DB_CONNECTION_PASS_CLINEPI}
      lookupCn: ${env:DB_CONNECTION_LDAP_CLINEPI}
    datasetPropertySchema: *edaDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_CLINEPI:-true}

  - targetName: ${env:DB_CONNECTION_NAME_CRYPTO:-CryptoDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_CRYPTO}
      password: ${env:DB_CONNECTION_PASS_CRYPTO}
      lookupCn: ${env:DB_CONNECTION_LDAP_CRYPTO}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_CRYPTO}
      password: ${env:DB_CONNECTION_PASS_CRYPTO}
      lookupCn: ${env:DB_CONNECTION_LDAP_CRYPTO}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_CRYPTO:-true}

  - targetName: ${env:DB_CONNECTION_NAME_FUNGI:-FungiDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_FUNGI}
      password: ${env:DB_CONNECTION_PASS_FUNGI}
      lookupCn: ${env:DB_CONNECTION_LDAP_FUNGI}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_FUNGI}
      password: ${env:DB_CONNECTION_PASS_FUNGI}
      lookupCn: ${env:DB_CONNECTION_LDAP_FUNGI}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_FUNGI:-true}

  - targetName: ${env:DB_CONNECTION_NAME_GIARDIA:-GiardiaDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_GIARDIA}
      password: ${env:DB_CONNECTION_PASS_GIARDIA}
      lookupCn: ${env:DB_CONNECTION_LDAP_GIARDIA}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_GIARDIA}
      password: ${env:DB_CONNECTION_PASS_GIARDIA}
      lookupCn: ${env:DB_CONNECTION_LDAP_GIARDIA}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_GIARDIA:-true}

  - targetName: ${env:DB_CONNECTION_NAME_HOST:-HostDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_HOST}
      password: ${env:DB_CONNECTION_PASS_HOST}
      lookupCn: ${env:DB_CONNECTION_LDAP_HOST}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_HOST}
      password: ${env:DB_CONNECTION_PASS_HOST}
      lookupCn: ${env:DB_CONNECTION_LDAP_HOST}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_HOST:-true}

  - targetName: ${env:DB_CONNECTION_NAME_MICROBIOME:-MicrobiomeDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_MICROBIOME}
      password: ${env:DB_CONNECTION_PASS_MICROBIOME}
      lookupCn: ${env:DB_CONNECTION_LDAP_MICROBIOME}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_MICROBIOME}
      password: ${env:DB_CONNECTION_PASS_MICROBIOME}
      lookupCn: ${env:DB_CONNECTION_LDAP_MICROBIOME}
    datasetPropertySchema: *edaDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_MICROBIOME:-true}

  - targetName: ${env:DB_CONNECTION_NAME_MICROSPORIDIA:-MicrosporidiaDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_MICROSPORIDIA}
      password: ${env:DB_CONNECTION_PASS_MICROSPORIDIA}
      lookupCn: ${env:DB_CONNECTION_LDAP_MICROSPORIDIA}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_MICROSPORIDIA}
      password: ${env:DB_CONNECTION_PASS_MICROSPORIDIA}
      lookupCn: ${env:DB_CONNECTION_LDAP_MICROSPORIDIA}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_MICROSPORIDIA:-true}

  - targetName: ${env:DB_CONNECTION_NAME_ORTHO:-OrthoMCL}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_ORTHO}
      password: ${env:DB_CONNECTION_PASS_ORTHO}
      lookupCn: ${env:DB_CONNECTION_LDAP_ORTHO}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_ORTHO}
      password: ${env:DB_CONNECTION_PASS_ORTHO}
      lookupCn: ${env:DB_CONNECTION_LDAP_ORTHO}
    enabled: ${env:DB_CONNECTION_ENABLED_ORTHO:-true}

  - targetName: ${env:DB_CONNECTION_NAME_PIROPLASMA:-PiroplasmaDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_PIROPLASMA}
      password: ${env:DB_CONNECTION_PASS_PIROPLASMA}
      lookupCn: ${env:DB_CONNECTION_LDAP_PIROPLASMA}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_PIROPLASMA}
      password: ${env:DB_CONNECTION_PASS_PIROPLASMA}
      lookupCn: ${env:DB_CONNECTION_LDAP_PIROPLASMA}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_PIROPLASMA:-true}

  - targetName: ${env:DB_CONNECTION_NAME_PLASMO:-PlasmoDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_PLASMO}
      password: ${env:DB_CONNECTION_PASS_PLASMO}
      lookupCn: ${env:DB_CONNECTION_LDAP_PLASMO}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_PLASMO}
      password: ${env:DB_CONNECTION_PASS_PLASMO}
      lookupCn: ${env:DB_CONNECTION_LDAP_PLASMO}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_PLASMO:-true}

  - targetName: ${env:DB_CONNECTION_NAME_TOXO:-ToxoDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_TOXO}
      password: ${env:DB_CONNECTION_PASS_TOXO}
      lookupCn: ${env:DB_CONNECTION_LDAP_TOXO}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_TOXO}
      password: ${env:DB_CONNECTION_PASS_TOXO}
      lookupCn: ${env:DB_CONNECTION_LDAP_TOXO}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_TOXO:-true}

  - targetName: ${env:DB_CONNECTION_NAME_TRICH:-TrichDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_TRICH}
      password: ${env:DB_CONNECTION_PASS_TRICH}
      lookupCn: ${env:DB_CONNECTION_LDAP_TRICH}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_TRICH}
      password: ${env:DB_CONNECTION_PASS_TRICH}
      lookupCn: ${env:DB_CONNECTION_LDAP_TRICH}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_TRICH:-true}

  - targetName: ${env:DB_CONNECTION_NAME_TRITRYP:-TriTrypDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_TRITRYP}
      password: ${env:DB_CONNECTION_PASS_TRITRYP}
      lookupCn: ${env:DB_CONNECTION_LDAP_TRITRYP}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_TRITRYP}
      password: ${env:DB_CONNECTION_PASS_TRITRYP}
      lookupCn: ${env:DB_CONNECTION_LDAP_TRITRYP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_TRITRYP:-true}

  - targetName: ${env:DB_CONNECTION_NAME_VECTOR:-VectorBase}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_VECTOR}
      password: ${env:DB_CONNECTION_PASS_VECTOR}
      lookupCn: ${env:DB_CONNECTION_LDAP_VECTOR}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_VECTOR}
      password: ${env:DB_CONNECTION_PASS_VECTOR}
      lookupCn: ${env:DB_CONNECTION_LDAP_VECTOR}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:DB_CONNECTION_ENABLED_VECTOR:-true}

  - targetName: ${env:DB_CONNECTION_NAME_UNIDB:-VEuPathDB}
    controlDb:
      username: ${env:DB_CONNECTION_CONTROL_SCHEMA_UNIDB}
      password: ${env:DB_CONNECTION_PASS_UNIDB}
      lookupCn: ${env:DB_CONNECTION_LDAP_UNIDB}
    dataDb:
      username: ${env:DB_CONNECTION_DATA_SCHEMA_UNIDB}
      password: ${env:DB_CONNECTION_PASS_UNIDB}
      lookupCn: ${env:DB_CONNECTION_LDAP_UNIDB}
    enabled: ${env:DB_CONNECTION_ENABLED_UNIDB:-false}

