$schema: https://veupathdb.github.io/vdi-service/schema/config/full-config.json

definitions:
  genomicsProjects: &genomicsProjects
  - AmoebaDB
  - CryptoDB
  - FungiDB
  - GiardiaDB
  - HostDB
  - MicrosporidiaDB
  - PiroplasmaDB
  - PlasmoDB
  - ToxoDB
  - TrichDB
  - TriTrypDB
  - VectorBase
  - VEuPathDB
  vdiSchemaPass: &vdiSchemaPass ${env:VDI_APPDB_SCHEMA_PASS}
  vdiControlSchema: &vdiControlSchema vdi_control_dev_${env:LOCATION_INDICATOR}
  vdiDataSchema: &vdiDataSchema vdi_datasets_dev_${env:LOCATION_INDICATOR}
  datasetPropertiesJsonSchemaFiles:
  - &genDatasetProps /schema/data/dataset-characteristics.genomics.json
  - &edaDatasetProps /schema/data/dataset-characteristics.eda.json

containerCore:
  http:
    bindPort: 80
    enableCors: true
  authentication:
    oauth:
      clientId: ${env:OAUTH_CLIENT_ID}
      clientSecret: ${env:OAUTH_CLIENT_SECRET}
      url: https://eupathdb.org/oauth
    adminToken: ${env:ADMIN_AUTH_TOKEN}

vdi:
  restService:
    enableJerseyTrace: true

  siteBuild: ${env:SITE_BUILD}

  ldap:
    servers: ${env:LDAP_SERVER}
    baseDn: ou=applications,dc=apidb,dc=org

  objectStore:
    bucketName: vdi
    https: false
    server:
      host: minio-external
    accessToken: minioUser
    secretKey: minioPass

  rabbit:
    global:
      connection:
        server: rabbit-external
        username: rabbitUser
        password: rabbitPass
        tls: false
      exchange:
        name: vdi-bucket-notifications
      queue:
        name: vdi-bucket-notifications
      routing:
        key: vdi-bucket-notifications

  daemons:
    reconciler:
      enabled: false

  kafka:
    servers:
    - kafka:9092

  cacheDb:
    username: vdi
    password: pgPass
    server: cache-db:5432

  plugins:
    bigwig:
      server: bigwig:80
      displayName: bigWig
      dataTypes:
      - name: bigwigfiles
        version: 1.0
      projectIds: *genomicsProjects
    biom:
      server: biom:80
      displayName: BIOM
      dataTypes:
      - name: biom
        version: 1.0
      projectIds:
      - MicrobiomeDB
    example:
      server: example:80
      displayName: Example
      dataTypes:
      - name: noop
        version: 1.0
    genelist:
      server: genelist:80
      displayName: Gene List
      dataTypes:
      - name: genelist
        version: 1.0
      projectIds: *genomicsProjects
    isasimple:
      server: isasimple:80
      displayName: ISA Study
      dataTypes:
      - name: isasimple
        version: 1.0
      projectIds:
      - ClinEpiDB
    noop:
      server: noop:80
      displayName: Lightweight
      dataTypes:
      - name: lightweight
        version: 1.0
      typeChangesEnabled: true
    phenotype:
      server: wrangler:80
      displayName: Phenotype
      dataTypes:
      - name: phenotype
        version: 1.0
      projectIds: *genomicsProjects
    rnaseq:
      server: rnaseq:80
      displayName: RNA-Seq
      dataTypes:
      - name: rnaseq
        version: 1.0
      projectIds: *genomicsProjects

  installTargets:
  - targetName: AmoebaDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:AMOEBA_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:AMOEBA_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:AMOEBA_ENABLED:-false}

  - targetName: ClinEpiDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:CLINEPI_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:CLINEPI_LDAP}
    datasetPropertySchema: *edaDatasetProps
    enabled: ${env:CLINEPI_ENABLED:-false}

  - targetName: CryptoDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:CRYPTO_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:CRYPTO_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:CRYPTO_ENABLED:-false}

  - targetName: FungiDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:FUNGI_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:FUNGI_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:FUNGI_ENABLED:-false}

  - targetName: GiardiaDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:GIARDIA_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:GIARDIA_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:GIARDIA_ENABLED:-false}

  - targetName: HostDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:HOST_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:HOST_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:HOST_ENABLED:-false}

  - targetName: MicrobiomeDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:MICROBIOME_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:MICROBIOME_LDAP}
    datasetPropertySchema: *edaDatasetProps
    enabled: ${env:MICROBIOME_ENABLED:-false}

  - targetName: MicrosporidiaDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:MICROSPORIDIA_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:MICROSPORIDIA_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:MICROSPORIDIA_ENABLED:-false}

  - targetName: OrthoMCL
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:ORTHO_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:ORTHO_LDAP}
    enabled: ${env:ORTHO_ENABLED:-false}

  - targetName: PiroplasmaDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:PIROPLASMA_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:PIROPLASMA_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:PIROPLASMA_ENABLED:-false}

  - targetName: PlasmoDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:PLASMO_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:PLASMO_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:PLASMO_ENABLED:-false}

  - targetName: ToxoDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:TOXO_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:TOXO_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:TOXO_ENABLED:-false}

  - targetName: TrichDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:TRICH_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:TRICH_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:TRICH_ENABLED:-false}

  - targetName: TriTrypDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:TRITRYP_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:TRITRYP_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:TRITRYP_ENABLED:-false}

  - targetName: VectorBase
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:VECTOR_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:VECTOR_LDAP}
    datasetPropertySchema: *genDatasetProps
    enabled: ${env:VECTOR_ENABLED:-false}

  - targetName: VEuPathDB
    controlDb:
      username: *vdiControlSchema
      password: *vdiSchemaPass
      lookupCn: ${env:UNIDB_LDAP}
    dataDb:
      username: *vdiDataSchema
      password: *vdiSchemaPass
      lookupCn: ${env:UNIDB_LDAP}
    enabled: ${env:UNIDB_ENABLED:-false}

