$schema: https://veupathdb.github.io/vdi-service/schema/config.json

definitions:
  genomicsProjects: &genomicsProjects
  - AmoebaDB
  - CryptoDB
  - FungiDB
  - GiardiaDB
  - HostDB
  - MicrosporidiaDB
  - PiroplasmaDB
  - PlasmoDB
  - ToxoDB
  - TrichDB
  - TriTrypDB
  - VectorBase
  - VEuPathDB
  vdiSchemaPass: &vdiSchemaPass ${env:VDI_APPDB_SCHEMA_PASS}

containerCore:
  authentication:
    oauth:
      clientId: ${env:OAUTH_CLIENT_ID}
      clientSecret: ${env:OAUTH_CLIENT_SECRET}
      url: https://eupathdb.org/oauth
      keyStoreFile: ${env:KEY_STORE_FILE}
      keyStorePass: ${env:KEY_STORE_PASS_PHRASE}
    adminToken: ${env:ADMIN_AUTH_TOKEN}

vdi:
  ldap:
    servers: ${env:LDAP_SERVER}
    baseDn: ${env:DB_LOOKUP_BASE_DN}
  siteBuild: ${env:SITE_BUILD}
  objectStore:
    bucketName: vdi-prod
    host: ${env:S3_HOST}
    accessToken: ${env:S3_ACCESS_TOKEN}
    secretKey: ${env:S3_SECRET_KEY}
  rabbit:
    global:
      connection:
        host: ${env:GLOBAL_RABBIT_HOST}
        user: ${env:GLOBAL_RABBIT_USERNAME}
        pass: ${env:GLOBAL_RABBIT_PASSWORD}
      exchange:
        name: vdi-bucket-notifications
      queue:
        name: vdi-bucket-notifications
      routing:
        key: vdi-bucket-notifications
  kafka:
    servers:
    - kafka:9092
    listeners:
    - PLAINTEXT://kafka:9092
  cacheDb:
    user: vdi
    pass: ${env:CACHE_DB_PASSWORD}
    host: cache-db:5432
  plugins:
    bigwig:
      server: bigwig:80
      displayName: bigWig
      dataType:
        name: bigwigfiles
        version: 1.0
      projectIds: *genomicsProjects
    biom:
      server: biom:80
      displayName: BIOM
      dataType:
        name: biom
        version: 1.0
      projectIds:
      - MicrobiomeDB
    genelist:
      server: genelist:80
      displayName: Gene List
      dataType:
        name: lightweight
        version: 1.0
      projectIds: *genomicsProjects
    isa:
      server: isasimple:80
      displayName: ISA Study
      dataType:
        name: isasimple
        version: 1.0
      projectIds:
      - ClinEpiDB
    noop:
      server: noop:80
      displayName: Lightweight
      dataType:
        name: lightweight
        version: 1.0
    phenotype:
      server: phenotype:80
      displayName: Phenotype
      dataType:
        name: phenotype
        version: 1.0
      projectIds: *genomicsProjects
    rnaSeq:
      server: rnaseq:80
      displayName: RNA-Seq
      dataType:
        name: rnaseq
        version: 1.0
      projectIds: *genomicsProjects
  targetDbs:
    amoeba:
      targetName: AmoebaDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_AMOEBA}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    clinepi:
      targetName: ClinEpiDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_CLINEPI}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    crypto:
      targetName: CryptoDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_CRYPTO}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    fungi:
      targetName: FungiDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_FUNGI}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    giardia:
      targetName: GiardiaDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_GIARDIA}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    host:
      targetName: HostDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_HOST}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    microbiome:
      targetName: MicrobiomeDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_MICROBIOME}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    microsporidia:
      targetName: MicrosporidiaDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_MICROSPORIDIA}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    ortho:
      targetName: OrthoMCL
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_ORTHO}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    piroplasma:
      targetName: PiroplasmaDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_PIROPLASMA}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    plasmo:
      targetName: PlasmoDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_PLASMO}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    toxo:
      targetName: ToxoDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_TOXO}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    trich:
      targetName: TrichDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_TRICH}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    tritryp:
      targetName: TriTrypDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_TRITRYP}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    uni:
      targetName: VEuPathDB
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_UNIDB}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
    vector:
      targetName: VectorBase
      pass: *vdiSchemaPass
      ldapCn: ${env:LDAP_VECTOR}
      dataSchema: vdi_datasets_prod_${env:LOCATION_INDICATOR}
      controlSchema: vdi_control_prod_${env:LOCATION_INDICATOR}
