version: "3.5"

networks:
  internal:
  traefik:
    external: true
  monitoring-ext:
    external: true
  rabbitmq:
    # Rabbit is local then the network is defined externally (set this to true)
    #
    # If rabbit is not local then the network is not defined externally and we
    # need to define it ourselves (set this to false)
    external: ${RABBITMQ_IS_LOCAL:-false}

volumes:
  cache-db-data:

services:
  cache-db:
    image: veupathdb/vdi-internal-db:${VDI_CACHE_DB_TAG:-latest}
    environment:
      POSTGRES_USER: vdi
      POSTGRES_PASSWORD: ${CACHE_DB_PASSWORD}
      POSTGRES_DB: vdi
    healthcheck:
      test: "pg_isready -U vdi -d vdi"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
    - internal
    volumes:
    - cache-db-data:/var/lib/postgresql/data
    labels:
    - "com.centurylinklabs.watchtower.enable=${VDI_POSTGRES_WATCHTOWER:-false}"

  kafka:
    image: veupathdb/apache-kafka:${VDI_KAFKA_TAG:-latest}
    healthcheck:
      test: nc -z localhost 9092 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_LISTENERS:-PLAINTEXT://kafka:9092}
    networks:
    - internal

  service:
    image: veupathdb/vdi-service:${VDI_SERVICE_TAG:-latest}
    build:
      context: ../
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
    - cache-db
    - kafka
    links:
    - cache-db
    - kafka
    - plugin-bigwig
    - plugin-biom
    - plugin-example
    - plugin-genelist
    - plugin-isasimple
    - plugin-rnaseq
    - plugin-phenotype
    networks:
    - internal
    - traefik
    - monitoring-ext
    - rabbitmq

    stop_grace_period: 1m
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN:?}
      CACHE_DB_PASSWORD: ${CACHE_DB_PASSWORD}

      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID:?}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET:?}
      KEY_STORE_FILE: ${KEY_STORE_FILE}
      KEY_STORE_PASS_PHRASE: ${KEY_STORE_PASS_PHRASE}

      S3_HOST: ${S3_HOST:?}
      S3_ACCESS_TOKEN: ${S3_ACCESS_TOKEN:?}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?}

      GLOBAL_RABBIT_HOST: ${GLOBAL_RABBIT_HOST:?}
      GLOBAL_RABBIT_USERNAME: ${GLOBAL_RABBIT_USERNAME:?}
      GLOBAL_RABBIT_PASSWORD: ${GLOBAL_RABBIT_PASSWORD:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}

    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${VDI_SERVICE_WATCHTOWER:-false}"
    - "traefik.http.services.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.loadbalancer.server.port=80"
    - "traefik.http.routers.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.rule=Host(`${TRAEFIK_VDI_HOST:-vdi-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.tls=${USE_TRAEFIK_SSL:-true}"
    - "traefik.http.routers.${TRAEFIK_SERVICE_ROUTER:-vdi-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
    - "traefik.docker.network=traefik"

  plugin-bigwig:
    image: veupathdb/vdi-plugin-bigwig:${VDI_PLUGIN_BIGWIG_TAG:-latest}
    networks:
      internal:
        aliases:
        - bigwig
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_BIGWIG_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}

  plugin-biom:
    image: veupathdb/vdi-plugin-biom:${VDI_PLUGIN_BIOM_TAG:-latest}
    networks:
      internal:
        aliases:
        - biom
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_BIOM_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}

  plugin-genelist:
    image: veupathdb/vdi-plugin-genelist:${VDI_PLUGIN_GENELIST_TAG:-latest}
    networks:
      internal:
        aliases:
        - genelist
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_GENELIST_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      DATASET_INSTALL_ROOT: /datasets
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${DB_LOOKUP_BASE_DN}
      SITE_BUILD: ${SITE_BUILD}
      LOCATION_INDICATOR: ${LOCATION_INDICATOR}

      LDAP_AMOEBA: ${LDAP_AMOEBA}
      LDAP_CRYPTO: ${LDAP_CRYPTO}
      LDAP_FUNGI: ${LDAP_FUNGI}
      LDAP_GIARDIA: ${LDAP_GIARDIA}
      LDAP_HOST: ${LDAP_HOST}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA}
      LDAP_PLASMO: ${LDAP_PLASMO}
      LDAP_TOXO: ${LDAP_TOXO}
      LDAP_TRICH: ${LDAP_TRICH}
      LDAP_TRITRYP: ${LDAP_TRITRYP}
      LDAP_VECTOR: ${LDAP_VECTOR}
      LDAP_ORTHO: ${LDAP_ORTHO}
      LDAP_CLINEPI: ${LDAP_CLINEPI}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME}
      LDAP_UNIDB: ${LDAP_UNIDB}

  plugin-isasimple:
    image: veupathdb/vdi-plugin-isasimple:${VDI_PLUGIN_ISASIMPLE_TAG:-latest}
    networks:
      internal:
        aliases:
        - isasimple
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_ISASIMPLE_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}

  plugin-noop:
    image: veupathdb/vdi-plugin-noop:${VDI_PLUGIN_NOOP_TAG:-latest}
    networks:
      internal:
        aliases:
        - noop
      monitoring-ext: { }
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_NOOP_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}

  plugin-phenotype:
    image: veupathdb/vdi-plugin-wrangler:${VDI_PLUGIN_WRANGLER_TAG:-latest}
    networks:
      internal:
        aliases:
        - phenotype
      monitoring-ext: { }
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_WRANGLER_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}

  plugin-rnaseq:
    image: veupathdb/vdi-plugin-rnaseq:${VDI_PLUGIN_RNASEQ_TAG:-latest}
    networks:
      internal:
        aliases:
        - rnaseq
      monitoring-ext: {}
    labels:
    - "prometheus.scrape_enabled=true"
    - "com.centurylinklabs.watchtower.enable=${PLUGIN_RNASEQ_WATCHTOWER:-false}"
    volumes:
    - type: bind
      source: ${DATASET_DIRECTORY_SOURCE_PATH}
      target: /datasets
    environment:
      JVM_ARGS: ${JVM_ARGS}
      JVM_MEM_ARGS: ${JVM_MEM_ARGS}

      LOCATION_INDICATOR: ${LOCATION_INDICATOR:?}

      SITE_BUILD: ${SITE_BUILD:?}

      # VPDB Application Database Connection Config
      LDAP_SERVER: ${LDAP_SERVER:?}
      DB_LOOKUP_BASE_DN: ${DB_LOOKUP_BASE_DN:?}
      VDI_APPDB_SCHEMA_PASS: ${VDI_APPDB_SCHEMA_PASS:?}
      LDAP_AMOEBA: ${LDAP_AMOEBA:?}
      LDAP_CRYPTO: ${LDAP_CRYPTO:?}
      LDAP_FUNGI: ${LDAP_FUNGI:?}
      LDAP_GIARDIA: ${LDAP_GIARDIA:?}
      LDAP_HOST: ${LDAP_HOST:?}
      LDAP_MICROSPORIDIA: ${LDAP_MICROSPORIDIA:?}
      LDAP_PIROPLASMA: ${LDAP_PIROPLASMA:?}
      LDAP_PLASMO: ${LDAP_PLASMO:?}
      LDAP_TOXO: ${LDAP_TOXO:?}
      LDAP_TRICH: ${LDAP_TRICH:?}
      LDAP_TRITRYP: ${LDAP_TRITRYP:?}
      LDAP_VECTOR: ${LDAP_VECTOR:?}
      LDAP_ORTHO: ${LDAP_ORTHO:?}
      LDAP_CLINEPI: ${LDAP_CLINEPI:?}
      LDAP_MICROBIOME: ${LDAP_MICROBIOME:?}
      LDAP_UNIDB: ${LDAP_UNIDB:?}
