#%RAML 1.0 Library

uses:
  common: "../../common.raml"

types:
  ServiceMetadataResponseBody:
    type: object
    additionalProperties: false
    properties:
      buildInfo: ServiceMetadataBuildInfoOutput
      configuration: ServiceConfigurationDetails
      features: ServiceFeatures

  ServiceMetadataBuildInfoOutput:
    type: object
    additionalProperties: false
    properties:
      gitTag: string
      gitCommit: string
      gitBranch: string
      gitUrl: string
      buildId: string
      buildNumber: string
      buildTime: string

  ServiceConfigurationDetails:
    type: object
    additionalProperties: false
    properties:
      api: APIServiceConfiguration
      daemons: DaemonConfiguration

  APIServiceConfiguration:
    type: object
    additionalProperties: false
    properties:
      maxUploadSize:
        type: integer
        format: int64
      userMaxStorageSize:
        type: integer
        format: int64

  DaemonConfiguration:
    type: object
    additionalProperties: false
    properties:
      reconciler: ReconcilerConfig

  ReconcilerConfig:
    type: object
    additionalProperties: false
    properties:
      enabled: boolean
      fullRunInterval: string
      slimRunInterval: string
      performDeletes: boolean

  ServiceFeatures:
    type: object
    additionalProperties: false
    properties:
      supportedArchiveTypes: string[]