#%RAML 1.0 Resource

displayName: VDI Plugins

get:
  displayName: List Enabled
  description: List the plugins currently registered with the VDI instance.
  queryParameters:
    project:
      displayName: Project Filter
      description: |
        Optional parameter that may be used to filter the results of this
        endpoint to only those that are allowed to be used with the target
        project.
        
        Valid values (non-case-sensitive):
        
        - AmoebaDB
        - ClinEpiDB
        - CryptoDB
        - FungiDB
        - GiardiaDB
        - HostDB
        - MicrobiomeDB
        - MicrosporidiaDB
        - PiroplasmaDB
        - PlasmoDB
        - ToxoDB
        - TrichDB
        - TriTrypDB
        - VectorBase
        - VEuPathDB
      type: string
      required: false
  responses:
    200:
      description: Success
      body:
        application/json:
          type: lib.PluginListItem[]
    401:
      description: Unauthorized
      body:
        application/json:
          type: lib.UnauthorizedError
    500:
      description: Internal Server Error
      body:
        application/json:
          type: lib.ServerError
