apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-registry
  namespace: vdi
data:
  # No-Op Plugin
  PLUGIN_HANDLER_NOOP_NAME: "noop"
  PLUGIN_HANDLER_NOOP_DISPLAY_NAME: "Example Plugin"
  PLUGIN_HANDLER_NOOP_VERSION: "1.0"
  PLUGIN_HANDLER_NOOP_ADDRESS: "plugin-example:80"
  PLUGIN_HANDLER_NOOP_PROJECT_IDS: ""

  # GeneList Plugin
  PLUGIN_HANDLER_GENELIST_NAME: "genelist"
  PLUGIN_HANDLER_GENELIST_DISPLAY_NAME: "Gene List"
  PLUGIN_HANDLER_GENELIST_VERSION: "1.0"
  PLUGIN_HANDLER_GENELIST_ADDRESS: "plugin-genelist:80"
  PLUGIN_HANDLER_GENELIST_PROJECT_IDS: "AmoebaDB,ClinEpiDB,CryptoDB,FungiDB,GiardiaDB,HostDB,MicrosporidiaDB,PiroplasmaDB,PlasmoDB,ToxoDB,TrichDB,TriTrypDB,VectorBase"

  # ISASimple Plugin
  PLUGIN_HANDLER_ISASIMPLE_NAME: "isa"
  PLUGIN_HANDLER_ISASIMPLE_DISPLAY_NAME: "ISA Study"
  PLUGIN_HANDLER_ISASIMPLE_VERSION: "1.0"
  PLUGIN_HANDLER_ISASIMPLE_ADDRESS: "plugin-isasimple:80"
  PLUGIN_HANDLER_ISASIMPLE_PROJECT_IDS: "ClinEpiDB"

  # BigWig Plugin
  PLUGIN_HANDLER_BIGWIG_NAME: "bigwigfiles"
  PLUGIN_HANDLER_BIGWIG_DISPLAY_NAME: "Bigwig"
  PLUGIN_HANDLER_BIGWIG_VERSION: "1.0"
  PLUGIN_HANDLER_BIGWIG_ADDRESS: "plugin-bigwig:80"
  PLUGIN_HANDLER_BIGWIG_PROJECT_IDS: "AmoebaDB,ClinEpiDB,CryptoDB,FungiDB,GiardiaDB,HostDB,MicrosporidiaDB,PiroplasmaDB,PlasmoDB,ToxoDB,TrichDB,TriTrypDB,VectorBase"

  # BigWig Plugin
  PLUGIN_HANDLER_BIOM_NAME: "biom"
  PLUGIN_HANDLER_BIOM_DISPLAY_NAME: "BIOM"
  PLUGIN_HANDLER_BIOM_VERSION: "1.0"
  PLUGIN_HANDLER_BIOM_ADDRESS: "plugin-biom:80"
  PLUGIN_HANDLER_BIOM_PROJECT_IDS: "MicrobiomeDB"

  # BigWig Plugin
  PLUGIN_HANDLER_RNASEQ_NAME: "rnaseq"
  PLUGIN_HANDLER_RNASEQ_DISPLAY_NAME: "RNA-Seq"
  PLUGIN_HANDLER_RNASEQ_VERSION: "1.0"
  PLUGIN_HANDLER_RNASEQ_ADDRESS: "plugin-rnaseq:80"
  PLUGIN_HANDLER_RNASEQ_PROJECT_IDS: "AmoebaDB,ClinEpiDB,CryptoDB,FungiDB,GiardiaDB,HostDB,MicrosporidiaDB,PiroplasmaDB,PlasmoDB,ToxoDB,TrichDB,TriTrypDB,VectorBase"
