= Example VDI Handler Plugin
:toc: left
:toclevels: 3
:repo-url: https://github.com/VEuPathDB/service-user-datasets
:handler-server-url: {repo-url}/tree/main/util-handler-server

This repository defines an example implementation of the VDI Handler Plugin API.

== Plugin Scripts

=== Import Script

The import script is the first phase of handling of an uploaded VDI dataset.
This script is responsible for performing the initial validation of the raw
input, and optionally transformation of that input into a form more suitable for
installation into target VEuPathDB sites.

The import script will be handed a collection of submitted dataset files, and is
expected to perform its processing, producing one or more output files which
will be used as the final form of the data to be installed into the target
VEuPathDB sites.

==== Inputs

As inputs the import script will be passed 2 parameters, an input directory path
and an output directory path.

[source, shell-session]
----
$ import /path/to/inputs /path/to/outputs
----

The input directory path will point to a temp directory that is populated with
the raw input files that will exist for the duration of the execution of the
import script.  After the import script has exited, the input directory will be
deleted.

The output directory path will point to a temp directory that is to be populated
by the import script.  The output files placed into the output directory will be
consumed by the link:{handler-server-url}[VDI Handler Server].  After the import
script has exited, the contents of the output directory will be collected, then
the directory will be deleted.

==== Outputs

As output, the script will be expected to write "installable" files to the
output directory handed to the import script on execution.

After the script execution has been completed, the files the import script
places in the output directory will be consumed by the
link:{handler-server-url}[VDI Handler Server] and will become the VDI dataset
bundle that is installed into the target VEuPathDB sites.

===== Reserved File Names

The import script may produce any files it needs, provided they are not named
with one of the following reserved file names.

`meta.json`:: This file name is reserved for the dataset's metadata file which
is produced by the link:{handler-server-url}[VDI Handler Server] itself after
the import script has completed execution.
+
If the import script _does_ produce a file named `meta.json`, the handler server
will throw an exception.

`manifest.json`:: This file name is reserved for the dataset's manifest file
which is produced by the link:{handler-server-url}[VDI Handler Server] itself
after the import script has completed execution.
+
If the import script _does_ produce a file named `manifest.json`, the handler
server will throw an exception.

`warnings.json`:: This file name is reserved for the dataset's validation
warning messages file which is produced by the
link:{handler-server-url}[VDI Handler Server] itself after the import script has
completed execution.
+
If the import script _does_ produce a file named `warnings.json`, the handler
server will throw an exception.

==== Logging

The import script is expected to log messages to 2 separate channels with
specific meaning assigned to each, `STDOUT` and `STDERR`.

`STDOUT` is expected to be used solely to emit validation warnings and errors.
All messages written to this channel will be surfaced to the submitter of the
VDI dataset being processed.

`STDERR` is expected to be used to emit general script log output.  All messages
written to this channel will be passed through to the standard logging of the
link:{handler-server-url}[VDI Handler Server].

==== Exit Codes

The import script is expected to conform to the following specification of
process exit codes.  Each exit code has an assigned meaning and is used to
determine how the link:{handler-server-url}[VDI Handler Server] process should
proceed after the script exits.

.Exit Codes
[source]
----
0   - Successful exit
1   - Failure due to validation errors
2   - Failure due to transformation errors
3+  - Failure due to unexpected/undefined error
----

=== Metadata Installation Script

=== Dataset Installation Script

=== Dataset Uninstallation Script