#%RAML 1.0 Resource

displayName: Plugins

get:
  displayName: List Plugins
  description: List the plugins currently registered with the VDI instance.
  queryParameters:
    project:
      displayName: Project Filter
      # language=markdown
      description: |
        Optional parameter that may be used to filter the results of this
        endpoint to only those that are allowed to be used with the target
        project.
      type: lib.InstallTargetID
      required: false
  responses:
    200:
      body: lib.PluginListItem[]
    401:
      body: lib.UnauthorizedError
    500:
      body: lib.ServerError
