name: Plugin Server Gradle Build

runs:
  using: composite
  steps:

  - name: Checkout Revision
    uses: actions/checkout@v4

  - name: Install Java
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: corretto

  - name: Install Gradle
    uses: gradle/actions/setup-gradle@v4
    with:
      cache-read-only: false

  - name: Run Gradle Build
    env:
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    shell: bash
    run: gradle --no-daemon :plugin-server:test :plugin-server:build
