#%RAML 1.0 Library

uses:
  common: ../../../common.raml

types:
  BrokenDatasetInstallReportBody:
    displayName: Failed Install Report
    additionalProperties: false
    properties:
      details?: BrokenDatasetInstallDetails[]
      ids?: common.VdiId[]

  BrokenDatasetInstallDetails:
    additionalProperties: false
    properties:
      datasetId: common.VdiId
      owner: common.UserId
      datasetType: common.DatasetTypeOutput
      installTargets:
        type: common.InstallTargetID[]
        minItems: 1
        uniqueItems: true
      status: common.DatasetStatusInfo

  BrokenImportListing:
    type: object
    additionalProperties: false
    properties:
      meta: BrokenImportListingMeta
      results: BrokenImportDetails[]

  BrokenImportListingMeta:
    type: object
    additionalProperties: false
    properties:
      count:
        description: Number of records in the result
        type: integer
      before?: string
      after?: string
      user?: common.UserId
      limit: integer
      offset: integer

  BrokenImportDetails:
    displayName: Broken Import Details
    additionalProperties: false
    properties:
      datasetId: common.VdiId
      owner: common.UserId
      datasetType: common.DatasetTypeOutput
      installTargets:
        type: common.InstallTargetID[]
        minItems: 1
        uniqueItems: true
      messages: string[]

  AllDatasetsListResponse:
    displayName: All Datasets Listing Response
    additionalProperties: false
    properties:
      meta: AllDatasetsListMeta
      results: AllDatasetsListEntry[]

  AllDatasetsListMeta:
    additionalProperties: false
    properties:
      count: integer
      offset: integer
      limit: integer
      total: integer

  AllDatasetsListEntry:
    additionalProperties: false
    properties:
      datasetId: common.VdiId
      owner: common.UserId
      datasetType: common.DatasetTypeOutput
      visibility: common.DatasetVisibility
      name: common.DatasetName
      origin: common.DatasetOrigin
      installTargets:
        type: common.InstallTargetID[]
        minItems: 1
        uniqueItems: true
      status: common.DatasetStatusInfo
      created: common.DatasetCreationDate
      isDeleted: boolean
      summary: common.DatasetSummary
      description?: common.DatasetDescription
      programName?: string
      projectName?: string

  SyncControlRecord:
    additionalProperties: false
    properties:
      sharesUpdateTime: datetime
      dataUpdateTime: datetime
      metaUpdateTime: datetime

  InternalDatasetDetails:
    additionalProperties: false
    properties:
      datasetType: common.DatasetTypeOutput
      owner: common.UserId
      isDeleted: boolean
      origin: common.DatasetOrigin
      created: common.DatasetCreationDate
      inserted: datetime
      name: common.DatasetName
      installTargets:
        type: common.InstallTargetID[]
        minItems: 1
        uniqueItems: true
      status: string
      importMessages: string[]
      visibility: common.DatasetVisibility
      summary: common.DatasetSummary
      description?: common.DatasetDescription
      syncControl?: SyncControlRecord
      uploadFiles?: string[]
      installFiles?: string[]
