#%RAML 1.0 Library

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.2.0/libraries/errors.raml

types:
  VDI-ID:
    displayName: VDI ID
    description: Unique VDI Dataset identifier string.
    type: string
    minLength: 14
    maxLength: 14
    pattern: ^[a-zA-Z0-9_-]{14}$

  User-ID:
    displayName: VEuPathDB User ID
    description: Unique user identifier
    type: integer
    format: int64
    minimum: 1
    maximum: 9223372036854775807

  ProjectID:
    displayName: Project ID
    description: |
      Name or ID of a target VEuPathDB project.

      Valid project IDs are:

      - AmoebaDB
      - ClinEpiDB
      - CryptoDB
      - FungiDB
      - GiardiaDB
      - HostDB
      - MicrobiomeDB
      - MicrosporidiaDB
      - PiroplasmaDB
      - PlasmoDB
      - ToxoDB
      - TrichDB
      - TriTrypDB
      - VectorBase
      - VEuPathDB
    type: string

  DatasetOwner:
    displayName: Dataset Owner
    description: Details about the owner of a VDI dataset.
    type: object
    additionalProperties: false
    properties:
      userId:
        displayName: Owner User ID
        description: VEuPathDB user ID of the owner of the dataset.
        type: User-ID
        required: true
      firstName:
        displayName: Owner First Name
        type: string
        required: false
      lastName:
        displayName: Owner Last Name
        type: string
        required: false
      email:
        displayName: Owner Email
        type: string
        required: false
      organization:
        displayName: Owner Organization
        type: string
        required: false

  DatasetTypeInfo:
    displayName: Dataset Type Info
    description: Information about a specific dataset type.
    type: object
    additionalProperties: false
    properties:
      name:
        displayName: Type Name
        type: string
        required: true
      displayName:
        displayName: Type Display Name
        description: |
          Display name for the type.  This field is ignored in requests and will
          always be present in responses.
        type: string
        required: false
      version:
        displayName: Type Version
        type: string
        required: true

  ShareOfferAction:
    type: string
    enum:
    - grant
    - revoke

  ShareReceiptAction:
    type: string
    enum:
    - accept
    - reject

  DatasetVisibility:
    type: string
    enum:
    - private
    - protected
    - public

  # region Dataset Status

  DatasetStatusInfo:
    displayName: Dataset Status Info
    description: Information about the import and install status of a dataset.
    type: object
    additionalProperties: false
    properties:
      import:
        type: DatasetImportStatus
        required: true
      install:
        type: DatasetInstallStatusEntry[]
        required: false
        default: null

  DatasetImportStatus:
    displayName: Dataset Import Status
    description: |
      Import status of the dataset.

      | Value         | Description                                                           |
      |---------------|-----------------------------------------------------------------------|
      | `queued`      | The dataset has not yet been processed and is waiting in the queue.   |
      | `in-progress` | The dataset is currently being import processed.                      |
      | `complete`    | The dataset has been processed and imported for installation.         |
      | `invalid`     | The dataset failed import validation.                                 |
      | `failed`      | The dataset import failed due to an internal server error.            |

    type: string
    enum:
    - queued
    - in-progress
    - complete
    - invalid
    - failed

  DatasetInstallStatus:
    displayName: Dataset Install Status
    type: string
    enum:
    - running
    - complete
    - failed-validation
    - failed-installation
    - ready-for-reinstall
    - missing-dependency

  DatasetInstallStatusEntry:
    displayName: Dataset Install Status Entry
    description: Entry in a list of install statuses for a dataset.
    type: object
    additionalProperties: false
    properties:
      projectId:
        type: ProjectID
        required: true
      metaStatus:
        type: DatasetInstallStatus
        required: false
      metaMessage:
        type: string
        required: false
      dataStatus:
        type: DatasetInstallStatus
        required: false
      dataMessage:
        type: string
        required: false

  # endregion Dataset Status

  DatasetDependency:
    type: object
    additionalProperties: false
    properties:
      resourceIdentifier:
        type: string
        required: true
      resourceDisplayName:
        type: string
        required: true
      resourceVersion:
        type: string
        required: true
