#%RAML 1.0 Library

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.3.0/libraries/errors.raml

types:
  DatasetCharacteristics:
    displayName: Dataset Characteristics
    description: |-
      Any-typed for compatibility with JaxRS and RAML.

      Actual schema definitions are available at:

      * [EDA Schema](https://veupathdb.github.io/vdi-service/dev/schema/data/dataset-characteristics.eda.json)
      * [Genomics Schema](https://veupathdb.github.io/vdi-service/dev/schema/data/dataset-characteristics.genomics.json)
    type: any

  DatasetContact:
    displayName: Dataset Contact
    additionalProperties: false
    properties:
      name:
        type: string
        minLength: 3
        maxLength: 300
      isPrimary?:
        type: boolean
        default: false
      email?:
        description: >-
          **IMPORTANT**: Required if `isPrimary == true`.
        type: string
        minLength: 5
        maxLength: 4000
      affiliation?:
        type: string
        maxLength: 4000
      city?:
        type: string
        maxLength: 200
      state?:
        type: string
        maxLength: 200
      country?:
        type: string
        maxLength: 200
      address?:
        type: string
        maxLength: 1000

  DatasetCreationDate:
    displayName: Dataset Creation Date
    description: Timestamp of the creation of the dataset
    type: datetime

  DatasetDependency:
    displayName: Dataset Dependency
    additionalProperties: false
    properties:
      resourceIdentifier:
        type: string
        minLength: 3
        maxLength: 50
      resourceDisplayName:
        type: string
        minLength: 3
        maxLength: 100
      resourceVersion:
        type: string
        minLength: 1
        maxLength: 50

  DatasetDescription:
    displayName: Dataset Description
    type: string
    description: Longform description of the dataset.

  DatasetHyperlink:
    displayName: Dataset Hyperlink
    type: object
    additionalProperties: false
    properties:
      url:
        type: string
        minLength: 7
        maxLength: 200
      text:
        type: string
        minLength: 3
        maxLength: 300
      description?:
        type: string
        maxLength: 4000
      isPublication?:
        type: boolean
        default: false

  DatasetImportStatus:
    displayName: Dataset Import Status
    description: |
      Import status of the dataset.

      | Value         | Description                                                           |
      |---------------|-----------------------------------------------------------------------|
      | `queued`      | The dataset has not yet been processed and is waiting in the queue.   |
      | `in-progress` | The dataset is currently being import processed.                      |
      | `complete`    | The dataset has been processed and imported for installation.         |
      | `invalid`     | The dataset failed import validation.                                 |
      | `failed`      | The dataset import failed due to an internal server error.            |

    type: string
    enum:
    - queued
    - in-progress
    - complete
    - invalid
    - failed

  DatasetInstallStatus:
    displayName: Dataset Install Status
    type: string
    enum:
    - running
    - complete
    - failed-validation
    - failed-installation
    - ready-for-reinstall
    - missing-dependency

  DatasetInstallStatusEntry:
    displayName: Dataset Install Target Status
    description: Entry in a list of install statuses for a dataset.
    additionalProperties: false
    properties:
      installTarget: InstallTargetID
      metaStatus: DatasetInstallStatus
      metaMessage?: string
      dataStatus?: DatasetInstallStatus
      dataMessage?: string

  DatasetMetaBase:
    displayName: Dataset Meta Base Fields
    type: object
    properties:
      # Fields that are different based on child type (and thus omitted here):
      # - datasetType (different format for post/get)
      # - visibility  (optional in post, required in get)
      # - sourceUrl   (only in get)
      #

      # Required Fields
      name: DatasetName
      summary: DatasetSummary
      origin: DatasetOrigin
      installTargets:
        description: IDs of the projects this dataset is being submitted to.
        type: InstallTargetID[]
        minItems: 1
        uniqueItems: true
      dependencies:
        type: DatasetDependency[]
        uniqueItems: true

      # Optional Fields
      contacts?:
        type: DatasetContact[]
        uniqueItems: true
      description?: DatasetDescription
      hyperlinks?:
        type: DatasetHyperlink[]
        uniqueItems: true
      organisms?:
        type: OrganismAbbreviation[]
        uniqueItems: true
      publications?:
        type: DatasetPublication[]
        uniqueItems: true
      shortName?: DatasetShortName
      shortAttribution?: DatasetShortAttribution
      properties?: DatasetCharacteristics
    additionalProperties: false

  DatasetName:
    displayName: Dataset Name
    type: string
    description: User-provided name for the dataset.
    minLength: 3
    maxLength: 1024

  DatasetOrigin:
    displayName: Dataset Origin
    description: |
      String representing the origin of the dataset.  Examples include
      `direct-upload`, `nephele`, or `galaxy`.
    type: string
    minLength: 3
    maxLength: 256

  DatasetOwner:
    displayName: Dataset Owner
    description: Details about the owner of a VDI dataset.
    additionalProperties: false
    properties:
      userId: UserId
      firstName?: string
      lastName?: string
      email?: string
      organization?: string

  DatasetPublication:
    displayName: Dataset Publication
    additionalProperties: false
    properties:
      pubMedId:
        type: string
        minLength: 3
        maxLength: 30
      citation?:
        type: string
        minLength: 3
        maxLength: 2000
      isPrimary?:
        type: boolean
        default: false

  DatasetRevision:
    displayName: Dataset Revision
    description: Dataset revision history entry.
    additionalProperties: false
    properties:
      action: DatasetRevisionAction
      timestamp: datetime
      revisionId: VdiId
      revisionNote: DatasetRevisionNote
      fileListUrl:
        description: URL to the file listing for the revision entry.
        type: string

  DatasetRevisionNote:
    displayName: Dataset Revision Note
    description: Note providing a reason and/or description for the revision.
    type: string
    minLength: 10
    maxLength: 4096

  DatasetRevisionAction:
    displayName: Dataset Revision Action
    type: string
    enum:
    - revise

  DatasetShortAttribution:
    type: string
    minLength: 3
    maxLength: 300

  DatasetShortName:
    type: string
    minLength: 3
    maxLength: 300

  DatasetSourceUrl:
    description: |
      URL of the dataset data source, if the dataset was uploaded via URL.
    type: string

  DatasetStatusInfo:
    description: Information about the import and install status of a dataset.
    additionalProperties: false
    properties:
      import: DatasetImportStatus
      install?: DatasetInstallStatusEntry[]

  DatasetSummary:
    description: Brief summary of the dataset.
    type: string
    minLength: 3
    maxLength: 4000

  DatasetTypeOutput:
    description: Details about a specific dataset type.
    additionalProperties: false
    properties:
      name:
        type: string
        minLength: 3
      version:
        type: string
        minLength: 1
      displayName:
        type: string
        minLength: 3

  DatasetTypeInput:
    additionalProperties: false
    properties:
      name:
        type: string
        minLength: 3
        maxLength: 128
      version:
        type: string
        minLength: 1
        maxLength: 32

  DatasetVisibility:
    type: string
    enum:
    - private
    - protected
    - public

  OrganismAbbreviation:
    type: string
    minLength: 3
    maxLength: 200

  PartialDate:
    displayName: Partial Datetime
    type: string
    minLength: 4
    description: |
      Subset of the RFC3339 format, requiring at least the 4 digit year, and may
      include additional precision, part by part.  Each part must be 'complete'
      and include standard preceding segment delimiters.

      Date segments that are omitted will be defaulted to the minimum valid
      value for that segment.  For example, If only the year value is provided,
      the assumed remainder is `-01-01T00:00:00.000Z`.

      Examples:
      * `2022`
      * `2022-03`
      * `2022-03-15`
      * `2022-03-15T16`
      * `2022-03-15T16:30`
      * `2022-03-15T16:30:12`
      * `2022-03-15T16:30:12Z`
      * `2022-03-15T16:30:12+04:00`
      * `2022-03-15T16:30:12.123Z`
      * `2022-03-15T16:30:12.123-06:00`

  InstallTargetID:
    description: Name or ID of a target VEuPathDB project, such as "PlasmoDB".
    type: string
    minLength: 5
    maxLength: 32

  ShareOfferAction:
    type: string
    enum:
    - grant
    - revoke

  ShareReceiptAction:
    type: string
    enum:
    - accept
    - reject

  UserId:
    description: VEuPathDB User ID
    type: integer
    format: int64
    minimum: 1
    maximum: 9223372036854775807

  VdiId:
    description: VDI dataset identifier
    type: string
    pattern: ^[a-zA-Z0-9_-]+$
