apiVersion: v1
kind: Pod
metadata:
  name: inter-pod-network-test-pod-1
  namespace: test1
spec:
  hostname: pod1
  containers:
  - name: test
    image: foxcapades/alpine-netcat:3.21.3
    command:
    - nc
    - -lp
    - "80"
    ports:
    - containerPort: 80
