apiVersion: v1
kind: Service
metadata:
  name: vdi
  namespace: vdi
spec:
  selector:
    stack: vdi
  ports:
    - name: rest-svc-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: rest-svc-https
      protocol: TCP
      port: 443
      targetPort: 80