on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - 'docs/vdi-api.html'
    - 'service/schema/**'
    - 'service/module/rest-service/api-schema/**'
    - 'service/module/rest-service/*.raml'
    - '.github/actions/api-doc-build/action.yml'
    - '.github/actions/api-doc-env/action.yml'
    - '.github/workflows/api-docs.yml'

jobs:
  prep:
    name: Get Doc Target Versions
    runs-on: ubuntu-latest
    outputs:
      prod_tag: ${{ steps.prod_version.outputs.version }}
      qa_tag: ${{ steps.qa_version.outputs.version }}
    steps:
    - name: Clone Production Tagger
      uses: actions/checkout@v4
      with:
        repository: 'VEuPathDB/tagger'
        ref: 'prod'
        token: '${{ secrets.GH_TOKEN }}'
    - name: Get Production Tag
      run: |-
        echo version=v$(grep vdi-service versions.yml | awk '{ print $2 }') >> "$GITHUB_OUTPUT"
      id: prod_version

    - name: Clone QA
      uses: actions/checkout@v4
      with:
        repository: 'VEuPathDB/tagger'
        ref: 'qa'
        token: '${{ secrets.GH_TOKEN }}'
    - name: Get QA Tag
      run: |-
        echo version=v$(grep vdi-service versions.yml | awk '{ print $2 }') >> "$GITHUB_OUTPUT"
      id: qa_version

  build:
    name: Build API Docs
    runs-on: ubuntu-latest
    needs: prep
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/api-doc-env

    - name: Build Dev Docs
      uses: ./.github/actions/api-doc-build
      with:
        ref: main
        output-dir: tmpdocs/dev
        gh-token: ${{ secrets.GH_TOKEN }}
        gh-user: ${{ secrets.GH_USERNAME }}

    - name: Build QA Docs
      uses: ./.github/actions/api-doc-build
      with:
        ref: '${{ needs.prep.outputs.qa_tag }}'
        output-dir: tmpdocs/qa
        gh-token: ${{ secrets.GH_TOKEN }}
        gh-user: ${{ secrets.GH_USERNAME }}

    - name: Build Prod Docs
      uses: ./.github/actions/api-doc-build
      with:
        ref: '${{ needs.prep.outputs.prod_tag }}'
        output-dir: tmpdocs/prod
        gh-token: ${{ secrets.GH_TOKEN }}
        gh-user: ${{ secrets.GH_USERNAME }}

    - uses: actions/upload-pages-artifact@v3
      with:
        path: tmpdocs/

  deploy:
    name: Deploy API Docs
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4
