on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - 'docs/vdi-api.html'
    - 'service/schema/**'

jobs:
  build:
    name: Build API Docs
    runs-on: ubuntu-latest
    steps:
    - name: Install Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
    - name: Install Gradle 8.14
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14'
    - name: Install NPM
      uses: actions/setup-node@v4
    - name: Install NPM Packages
      run: npm i -g raml2html raml2html-modern-theme
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Get Production Tag
      run: |-
        git clone --depth 1 -b prod https://github.com/VEuPathDB/tagger
        cd tagger
        echo version=$(grep vdi-service versions.yml | awk '{ print $2 }') >> "$GITHUB_OUTPUT"
        rm -rf .
      id: prod_version
    - name: Build Branch Docs
      run: make generate-service-docs OUTPUT_DOC_DIR=tmpdocs/dev/
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Build Production Docs
      run: |-
        mkdir tmpdocs/prod/
        git checkout ${{ steps.prod_version.outputs.version }}
        cp docs/vdi-api.html tmpdocs/prod/
    - uses: actions/upload-pages-artifact@v3
      with:
        path: tmpdocs/
  deploy:
    name: Deploy API Docs
    runs-on: ubuntu-latest
    needs:
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4
