on:
  push:
    branches:
    - main
    paths:
    - 'docs/vdi-api.html'

jobs:
  build:
    name: Build API Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: docs/
        compression-level: 9
  deploy:
    name: Deploy API Docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4
