on:
  push:
    branches:
    - main
    paths:
    - 'docs/vdi-api.html'

jobs:
  publish-api-docs:
    name: Publish API Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/
    - name: Deploy
      uses: actions/deploy-pages@v4
