on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - 'docs/vdi-api.html'

jobs:
  build:
    name: Build API Docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main
      uses: actions/checkout@v4
    - name: Copy Docs
      run: cp -r docs/ docs-for-upload/
    - name: Checkout Feature
      uses: actions/checkout@v4
      with:
        ref: feature-data-updates
        clean: 'false'
    - name: Copy Schema
      run: cp -r service/schema/config/ docs-for-upload/schema/
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs-for-upload/
  deploy:
    name: Deploy API Docs
    runs-on: ubuntu-latest
    needs:
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4
