name: VDI API Docs

on:
  workflow_dispatch: {}
  push:
    tags-ignore:
    - '*-*'
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      DOC_BUILD_DIR: ${{github.workspace}}/build/generated-docs
      PUBLISH_DIR: ${{ case(github.ref_name == 'main', 'latest', github.ref_name) }}

    steps:
    - name: Clone Repo
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: corretto

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Using fork that corrects schema reference links
    - name: Install Schema Doc Generator
      run: pip install git+https://github.com/Foxcapades/json-schema-for-humans

    - name: Install NPM
      uses: actions/setup-node@v4

    - name: Install NPM Packages
      shell: bash
      run: npm i -g raml2html raml2html-modern-theme

    - name: Generate Server Docs
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: >-
        gradle -P DOC_BUILD_DIR=$DOC_BUILD_DIR/core \
               -P DOC_FILE_NAME=index.html \
               :core:generate-raml-docs

    - name: Merge and Convert JSON Schema
      run: |-
        gradle -P SCHEMA_BUILD_DIR=$DOC_BUILD_DIR \
          :common:config:compile-config-schema

    - name: Generate Configuration Docs
      run: >-
        generate-schema-doc \
          --config expand_buttons \
          --config examples_as_yaml \
          --config no_link_to_reused_ref \
          $DOC_BUILD_DIR/schema/config/full-config.json \
          $DOC_BUILD_DIR/schema/config/full-config.html
        generate-schema-doc \
          --config expand_buttons \
          --config examples_as_yaml \
          --config no_link_to_reused_ref \
          $DOC_BUILD_DIR/schema/config/plugin-config.json \
          $DOC_BUILD_DIR/schema/config/plugin-config.html

    - name: Checkout Docs Branch
      uses: actions/checkout@v4
      with:
        clean: 'false'
        ref: gh-pages

    - name: Copy & Commit Docs
      run: >-
        rm -rf ${{ env.PUBLISH_DIR }};
        cp -r ${{ env.DOC_BUILD_DIR }} ${{ env.PUBLISH_DIR }};
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
        git config --local user.name "github-actions[bot]";
        git add ${{ env.PUBLISH_DIR }};
        git commit -m "create/update ${{ env.PUBLISH_DIR }}";

    - name: Push Docs
      uses: ad-m/github-push-action@v1.0.0
      with:
        branch: gh-pages
