on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - 'docs/vdi-api.html'

jobs:
  build:
    name: Build API Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
    - uses: gradle/actions/setup-gradle@v4
    - uses: actions/setup-node@v4
    - name: Checkout Feature
      uses: actions/checkout@v4
      with:
        ref: feature-data-updates
    - name: Build Branch Docs
      run: make generate-service-docs OUTPUT_DOC_DIR=docs-for-upload
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Checkout Main
      uses: actions/checkout@v4
      with:
        clean: 'false'
    - name: Copy Docs
      run: |
        cp docs-for-upload/vdi-api.html docs-for-upload/vdi-api-feat.html
        cp docs/vdi-api.html docs-for-upload
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs-for-upload/
  deploy:
    name: Deploy API Docs
    runs-on: ubuntu-latest
    needs:
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v4
