on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  gradle-build:
    name: Main Branch Code Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - name: Build
      run: |-
        gradle :core:build :core:test
        gradle :plugin-server:build :plugin-server:test
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
