on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run Gradle Build
      uses: veupathdb/vdi-service/.github/workflows/gradle-build.yml@main
      with:
        name: Scheduled Development Build
        branch: development
