on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  build:
    uses: veupathdb/vdi-service/.github/workflows/gradle-build.yml@main
    with:
      name: Scheduled Development Build
      branch: main
