on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  gradle-build:
    name: '${{ inputs.name }}'
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        ref: '${{ inputs.branch }}'
    - name: Init Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - name: Gradle Build
      run: ./gradlew build test --no-daemon
