name: Plugin Server Release

on:
  workflow_dispatch: { }
  push:
    tags:
    - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/plugin-server-build.yml

    - name: Run ShadowJar
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        gradle --no-daemon :plugin-server:shadowJar

    - name: Create Server Archive
      run: |-
        mkdir -p tmp/etc/vdi
        cp project/plugin-server/build/libs/service.jar tmp
        cp project/plugin-server/startup.sh tmp
        cp config/halfway-config.yml tmp/etc/vdi/config.yml
        cd tmp
        tar -czf plugin-server.tar.gz *

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: ${{contains(github.ref_name, '-')}}
        draft: false
        files: tmp/plugin-server.tar.gz
        generate_release_notes: true
