name: Build Plugin Server

on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request_target:
    branches:
    - main
    paths:
    - 'project/common/**'
    - 'project/plugin-server/**'
    - 'project/conventions/**'
    - 'gradle/common.versions.toml'
    - 'gradle/libs.versions.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/build-plugin-server
