name: Plugin Server Release

on:
  push:
    tags:
    - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Revision
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto

    - name: Install Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Run Gradle Build
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |-
        gradle :plugin-server:test :plugin-server:shadowJar
        mv -t . project/plugin-server/build/libs/service.jar
        sha256sum service.jar | cut -b1-64 | tr -d '\n' > service.jar.sha256
        md5sum service.jar | cut -b1-32 | tr -d '\n' > service.jar.md5
        sed "s/##VERSION_TEMPLATE##/${{steps.version.outputs.release}}/" scripts/docker-download.sh > docker-download.sh

    - name: Create Server Archive
      run: |-
        mkdir -p tmp/etc/vdi
        cp project/plugin-server/build/libs/service.jar tmp
        cp project/plugin-server/startup.sh tmp
        cp config/halfway-config.yml tmp/etc/vdi/config.yml
        cd tmp
        tar -czf plugin-server.tar.gz *

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: ${{contains(github.ref_name, '-')}}
        files: tmp/plugin-server.tar.gz
        generate_release_notes: true
