name: Release Plugin Server

on:
  workflow_dispatch: { }
  push:
    tags:
    - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-plugin-server
      with:
        gh-token: ${{ secrets.GH_TOKEN }}
        gh-user: ${{ secrets.GH_USERNAME }}

    - name: Run ShadowJar
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: gradle :plugin-server:shadowJar

    - name: Create Server Archive
      run: |-
        mkdir -p tmp/etc/vdi
        cp project/plugin-server/build/libs/service.jar tmp
        cp project/plugin-server/startup.sh tmp
        cp config/halfway-config.yml tmp/etc/vdi/config.yml
        cd tmp
        tar -czf plugin-server.tar.gz *

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: ${{contains(github.ref_name, '-')}}
        draft: false
        files: tmp/plugin-server.tar.gz
        generate_release_notes: true

  plugin-bigwig:
    needs:
    - publish
    uses: VEuPathDB/vdi-plugin-bigwig/.github/workflows/update-plugin-server.yml@main
    with:
      tag: ${{ github.ref_name }}
      plugin: bigwig
      token: ${{ secrets.VDI_BUILD_TREE_TOKEN }}
  plugin-example:
    needs:
    - publish
    uses: VEuPathDB/vdi-plugin-example/.github/workflows/update-plugin-server.yml@main
    with:
      tag: ${{ github.ref_name }}
      plugin: example
      token: ${{ secrets.VDI_BUILD_TREE_TOKEN }}
  plugin-genelist:
    needs:
    - publish
    uses: VEuPathDB/vdi-plugin-genelist/.github/workflows/update-plugin-server.yml@main
    with:
      tag: ${{ github.ref_name }}
      plugin: genelist
      token: ${{ secrets.VDI_BUILD_TREE_TOKEN }}
  plugin-isasimple:
    needs:
    - publish
    uses: VEuPathDB/vdi-plugin-isasimple/.github/workflows/update-plugin-server.yml@main
    with:
      tag: ${{ github.ref_name }}
      plugin: isasimple
      token: ${{ secrets.VDI_BUILD_TREE_TOKEN }}
  plugin-rnaseq:
    needs:
    - publish
    uses: VEuPathDB/vdi-plugin-rnaseq/.github/workflows/update-plugin-server.yml@main
    with:
      tag: ${{ github.ref_name }}
      plugin: rnaseq
      token: ${{ secrets.VDI_BUILD_TREE_TOKEN }}
  plugin-wrangler:
    needs:
    - publish
    uses: VEuPathDB/vdi-plugin-wrangler/.github/workflows/update-plugin-server.yml@main
    with:
      tag: ${{ github.ref_name }}
      plugin: wrangler
      token: ${{ secrets.VDI_BUILD_TREE_TOKEN }}
