on:
  pull_request:
    branches:
    - qa

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Init Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - name: Gradle Build
      run: ./gradlew build test --no-daemon
